/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { artifactsSetVisibility } from "../../funcs/artifactsSetVisibility.js";
import * as operations from "../../sdk/models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.SetVisibilityRequest$inboundSchema,
};

export const tool$artifactsSetVisibility: ToolDefinition<typeof args> = {
  name: "artifacts-set-visibility",
  description: `Set visibility of a namespace with an existing metadata entry`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await artifactsSetVisibility(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
