/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { codeSamplesGet } from "../../funcs/codeSamplesGet.js";
import * as operations from "../../sdk/models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetCodeSamplesRequest$inboundSchema,
};

export const tool$codeSamplesGet: ToolDefinition<typeof args> = {
  name: "code-samples-get",
  description: `Retrieve usage snippets

Retrieve usage snippets from an OpenAPI document stored in the registry. Supports filtering by language and operation ID.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await codeSamplesGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
