/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { organizationsGetSubscription } from "../../funcs/organizationsGetSubscription.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$organizationsGetSubscription: ToolDefinition = {
  name: "organizations-get-subscription",
  description: `Get organization subscription

Returns the subscription status for the current organization`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await organizationsGetSubscription(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
