/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { organizationsGetAll } from "../../funcs/organizationsGetAll.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$organizationsGetAll: ToolDefinition = {
  name: "organizations-get-all",
  description: `Get organizations for a user

Returns a list of organizations a user has access too`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await organizationsGetAll(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
