/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { reportsGetLintingReportSignedUrl } from "../../funcs/reportsGetLintingReportSignedUrl.js";
import * as operations from "../../sdk/models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetLintingReportSignedUrlRequest$inboundSchema,
};

export const tool$reportsGetLintingReportSignedUrl: ToolDefinition<
  typeof args
> = {
  name: "reports-get-linting-report-signed-url",
  description:
    `Get the signed access url for the linting reports for a particular document.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await reportsGetLintingReportSignedUrl(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
