/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { workspacesGetAll } from "../../funcs/workspacesGetAll.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$workspacesGetAll: ToolDefinition = {
  name: "workspaces-get-all",
  description: `Get workspaces for a user

Returns a list of workspaces a user has access too`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await workspacesGetAll(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
