/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { workspacesGetPublishingToken } from "../../funcs/workspacesGetPublishingToken.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$workspacesGetPublishingToken: ToolDefinition = {
  name: "workspaces-get-publishing-token",
  description: `Get publishing tokens for a workspace

Returns a publishing token for the current workspace`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await workspacesGetPublishingToken(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
