/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { workspacesGetByID } from "../../funcs/workspacesGetByID.js";
import * as operations from "../../sdk/models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetWorkspaceRequest$inboundSchema,
};

export const tool$workspacesGetByID: ToolDefinition<typeof args> = {
  name: "workspaces-get-by-ID",
  description: `Get workspace

Get information about a particular workspace.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await workspacesGetByID(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
