/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Request body of tags to add to a revision
 */
export class AddTags extends SpeakeasyBase {
    /**
     * revision digest to add tags too sha256:...
     */
    @SpeakeasyMetadata()
    @Expose({ name: "revision_digest" })
    revisionDigest: string;

    /**
     * string tags to add to the revision
     */
    @SpeakeasyMetadata()
    @Expose({ name: "tags" })
    tags: string[];
}
