/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type BillingEmailRequest = {
  /**
   * The billing email address to set
   */
  billingEmail: string;
};

/** @internal */
export const BillingEmailRequest$inboundSchema: z.ZodType<
  BillingEmailRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  billing_email: z.string(),
}).transform((v) => {
  return remap$(v, {
    "billing_email": "billingEmail",
  });
});
/** @internal */
export type BillingEmailRequest$Outbound = {
  billing_email: string;
};

/** @internal */
export const BillingEmailRequest$outboundSchema: z.ZodType<
  BillingEmailRequest$Outbound,
  z.ZodTypeDef,
  BillingEmailRequest
> = z.object({
  billingEmail: z.string(),
}).transform((v) => {
  return remap$(v, {
    billingEmail: "billing_email",
  });
});

export function billingEmailRequestToJSON(
  billingEmailRequest: BillingEmailRequest,
): string {
  return JSON.stringify(
    BillingEmailRequest$outboundSchema.parse(billingEmailRequest),
  );
}
export function billingEmailRequestFromJSON(
  jsonString: string,
): SafeParseResult<BillingEmailRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BillingEmailRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BillingEmailRequest' from JSON`,
  );
}
