/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  SpecBillingBreakdown,
  SpecBillingBreakdown$inboundSchema,
  SpecBillingBreakdown$Outbound,
  SpecBillingBreakdown$outboundSchema,
} from "./specbillingbreakdown.js";

/**
 * Contains the billing operations breakdown for an organization
 */
export type BillingOperationsResponse = {
  /**
   * Billing breakdown for each spec/namespace
   */
  specs: Array<SpecBillingBreakdown>;
  /**
   * Total billable units (operations x targets per spec)
   */
  totalBillableUnits: number;
  /**
   * Total count of unique operations across all specs
   */
  totalUniqueOperations: number;
};

/** @internal */
export const BillingOperationsResponse$inboundSchema: z.ZodType<
  BillingOperationsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  specs: z.array(SpecBillingBreakdown$inboundSchema),
  total_billable_units: z.number().int(),
  total_unique_operations: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "total_billable_units": "totalBillableUnits",
    "total_unique_operations": "totalUniqueOperations",
  });
});
/** @internal */
export type BillingOperationsResponse$Outbound = {
  specs: Array<SpecBillingBreakdown$Outbound>;
  total_billable_units: number;
  total_unique_operations: number;
};

/** @internal */
export const BillingOperationsResponse$outboundSchema: z.ZodType<
  BillingOperationsResponse$Outbound,
  z.ZodTypeDef,
  BillingOperationsResponse
> = z.object({
  specs: z.array(SpecBillingBreakdown$outboundSchema),
  totalBillableUnits: z.number().int(),
  totalUniqueOperations: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    totalBillableUnits: "total_billable_units",
    totalUniqueOperations: "total_unique_operations",
  });
});

export function billingOperationsResponseToJSON(
  billingOperationsResponse: BillingOperationsResponse,
): string {
  return JSON.stringify(
    BillingOperationsResponse$outboundSchema.parse(billingOperationsResponse),
  );
}
export function billingOperationsResponseFromJSON(
  jsonString: string,
): SafeParseResult<BillingOperationsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BillingOperationsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BillingOperationsResponse' from JSON`,
  );
}
