/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const BillingAddOn = {
  Webhooks: "webhooks",
  SDKTesting: "sdk_testing",
  CustomCodeRegions: "custom_code_regions",
  SnippetAi: "snippet_ai",
} as const;
export type BillingAddOn = OpenEnum<typeof BillingAddOn>;

/** @internal */
export const BillingAddOn$inboundSchema: z.ZodType<
  BillingAddOn,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(BillingAddOn);
/** @internal */
export const BillingAddOn$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  BillingAddOn
> = openEnums.outboundSchema(BillingAddOn);
