/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * A request to configure a GitHub repository for mintlify
 */
export type GithubConfigureMintlifyRepoRequest = {
  /**
   * The input OpenAPI document
   */
  input: string;
  /**
   * The GitHub organization name
   */
  org: string;
  /**
   * The overlays to apply
   */
  overlays: Array<string>;
  /**
   * The GitHub repository name
   */
  repo: string;
  /**
   * The subdirectory (location of mint.json)
   */
  subdirectory?: string | undefined;
};

/** @internal */
export const GithubConfigureMintlifyRepoRequest$inboundSchema: z.ZodType<
  GithubConfigureMintlifyRepoRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  input: z.string(),
  org: z.string(),
  overlays: z.array(z.string()),
  repo: z.string(),
  subdirectory: z.string().optional(),
});
/** @internal */
export type GithubConfigureMintlifyRepoRequest$Outbound = {
  input: string;
  org: string;
  overlays: Array<string>;
  repo: string;
  subdirectory?: string | undefined;
};

/** @internal */
export const GithubConfigureMintlifyRepoRequest$outboundSchema: z.ZodType<
  GithubConfigureMintlifyRepoRequest$Outbound,
  z.ZodTypeDef,
  GithubConfigureMintlifyRepoRequest
> = z.object({
  input: z.string(),
  org: z.string(),
  overlays: z.array(z.string()),
  repo: z.string(),
  subdirectory: z.string().optional(),
});

export function githubConfigureMintlifyRepoRequestToJSON(
  githubConfigureMintlifyRepoRequest: GithubConfigureMintlifyRepoRequest,
): string {
  return JSON.stringify(
    GithubConfigureMintlifyRepoRequest$outboundSchema.parse(
      githubConfigureMintlifyRepoRequest,
    ),
  );
}
export function githubConfigureMintlifyRepoRequestFromJSON(
  jsonString: string,
): SafeParseResult<GithubConfigureMintlifyRepoRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GithubConfigureMintlifyRepoRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GithubConfigureMintlifyRepoRequest' from JSON`,
  );
}
