/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * A request to configure GitHub code samples
 */
export type GithubConfigureCodeSamplesRequest = {
  /**
   * The GitHub organization name
   */
  org: string;
  /**
   * The GitHub repository name
   */
  repo: string;
  /**
   * The target name for the code samples
   */
  targetName: string;
};

/** @internal */
export const GithubConfigureCodeSamplesRequest$inboundSchema: z.ZodType<
  GithubConfigureCodeSamplesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  org: z.string(),
  repo: z.string(),
  targetName: z.string(),
});
/** @internal */
export type GithubConfigureCodeSamplesRequest$Outbound = {
  org: string;
  repo: string;
  targetName: string;
};

/** @internal */
export const GithubConfigureCodeSamplesRequest$outboundSchema: z.ZodType<
  GithubConfigureCodeSamplesRequest$Outbound,
  z.ZodTypeDef,
  GithubConfigureCodeSamplesRequest
> = z.object({
  org: z.string(),
  repo: z.string(),
  targetName: z.string(),
});

export function githubConfigureCodeSamplesRequestToJSON(
  githubConfigureCodeSamplesRequest: GithubConfigureCodeSamplesRequest,
): string {
  return JSON.stringify(
    GithubConfigureCodeSamplesRequest$outboundSchema.parse(
      githubConfigureCodeSamplesRequest,
    ),
  );
}
export function githubConfigureCodeSamplesRequestFromJSON(
  jsonString: string,
): SafeParseResult<GithubConfigureCodeSamplesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GithubConfigureCodeSamplesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GithubConfigureCodeSamplesRequest' from JSON`,
  );
}
