/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Annotations } from "./annotations";
import { V2Descriptor } from "./v2descriptor";
import { Expose, Type } from "class-transformer";

/**
 * Returns the requested manifest file
 */
export class Manifest extends SpeakeasyBase {
    /**
     * Annotations
     */
    @SpeakeasyMetadata()
    @Expose({ name: "annotations" })
    @Type(() => Annotations)
    annotations?: Annotations;

    /**
     * Type of artifact
     */
    @SpeakeasyMetadata()
    @Expose({ name: "artifactType" })
    artifactType?: string;

    /**
     * List of V2 image layer information
     */
    @SpeakeasyMetadata({ elemType: V2Descriptor })
    @Expose({ name: "layers" })
    @Type(() => V2Descriptor)
    layers?: V2Descriptor[];

    /**
     * Media type usually application/vnd.docker.distribution.manifest.v2+json if this is in the accept header
     */
    @SpeakeasyMetadata()
    @Expose({ name: "mediaType" })
    mediaType?: string;

    /**
     * Schema version
     */
    @SpeakeasyMetadata()
    @Expose({ name: "schemaVersion" })
    schemaVersion?: number;
}
