/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { OASInfo } from "./oasinfo";
import { OASOperation } from "./oasoperation";
import { Expose, Type } from "class-transformer";

export class OASSummary extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "info" })
    @Type(() => OASInfo)
    info: OASInfo;

    @SpeakeasyMetadata({ elemType: OASOperation })
    @Expose({ name: "operations" })
    @Type(() => OASOperation)
    operations: OASOperation[];
}
