/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  EventType,
  EventType$inboundSchema,
  EventType$outboundSchema,
} from "./eventtype.js";
import {
  SubscriptionType,
  SubscriptionType$inboundSchema,
  SubscriptionType$outboundSchema,
} from "./subscriptiontype.js";

/**
 * A subscription to a registry event
 */
export type RegistrySubscription = {
  createdAt: Date;
  deletedAt?: Date | undefined;
  eventType: EventType;
  id: string;
  namespaceName: string;
  subscriptionSettings: string;
  subscriptionType: SubscriptionType;
  tags?: Array<string> | undefined;
  updatedAt: Date;
  workspaceId: string;
};

/** @internal */
export const RegistrySubscription$inboundSchema: z.ZodType<
  RegistrySubscription,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  deleted_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  event_type: EventType$inboundSchema,
  id: z.string(),
  namespace_name: z.string(),
  subscription_settings: z.string(),
  subscription_type: SubscriptionType$inboundSchema,
  tags: z.array(z.string()).optional(),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  workspace_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "deleted_at": "deletedAt",
    "event_type": "eventType",
    "namespace_name": "namespaceName",
    "subscription_settings": "subscriptionSettings",
    "subscription_type": "subscriptionType",
    "updated_at": "updatedAt",
    "workspace_id": "workspaceId",
  });
});

/** @internal */
export type RegistrySubscription$Outbound = {
  created_at: string;
  deleted_at?: string | undefined;
  event_type: string;
  id: string;
  namespace_name: string;
  subscription_settings: string;
  subscription_type: string;
  tags?: Array<string> | undefined;
  updated_at: string;
  workspace_id: string;
};

/** @internal */
export const RegistrySubscription$outboundSchema: z.ZodType<
  RegistrySubscription$Outbound,
  z.ZodTypeDef,
  RegistrySubscription
> = z.object({
  createdAt: z.date().transform(v => v.toISOString()),
  deletedAt: z.date().transform(v => v.toISOString()).optional(),
  eventType: EventType$outboundSchema,
  id: z.string(),
  namespaceName: z.string(),
  subscriptionSettings: z.string(),
  subscriptionType: SubscriptionType$outboundSchema,
  tags: z.array(z.string()).optional(),
  updatedAt: z.date().transform(v => v.toISOString()),
  workspaceId: z.string(),
}).transform((v) => {
  return remap$(v, {
    createdAt: "created_at",
    deletedAt: "deleted_at",
    eventType: "event_type",
    namespaceName: "namespace_name",
    subscriptionSettings: "subscription_settings",
    subscriptionType: "subscription_type",
    updatedAt: "updated_at",
    workspaceId: "workspace_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RegistrySubscription$ {
  /** @deprecated use `RegistrySubscription$inboundSchema` instead. */
  export const inboundSchema = RegistrySubscription$inboundSchema;
  /** @deprecated use `RegistrySubscription$outboundSchema` instead. */
  export const outboundSchema = RegistrySubscription$outboundSchema;
  /** @deprecated use `RegistrySubscription$Outbound` instead. */
  export type Outbound = RegistrySubscription$Outbound;
}

export function registrySubscriptionToJSON(
  registrySubscription: RegistrySubscription,
): string {
  return JSON.stringify(
    RegistrySubscription$outboundSchema.parse(registrySubscription),
  );
}

export function registrySubscriptionFromJSON(
  jsonString: string,
): SafeParseResult<RegistrySubscription, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RegistrySubscription$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RegistrySubscription' from JSON`,
  );
}
