/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const Type = {
  Linting: "linting",
  Changes: "changes",
} as const;
export type Type = ClosedEnum<typeof Type>;

export type Report = {
  type?: Type | undefined;
};

/** @internal */
export const Type$inboundSchema: z.ZodNativeEnum<typeof Type> = z.nativeEnum(
  Type,
);
/** @internal */
export const Type$outboundSchema: z.ZodNativeEnum<typeof Type> =
  Type$inboundSchema;

/** @internal */
export const Report$inboundSchema: z.ZodType<Report, z.ZodTypeDef, unknown> = z
  .object({
    type: Type$inboundSchema.optional(),
  });
/** @internal */
export type Report$Outbound = {
  type?: string | undefined;
};

/** @internal */
export const Report$outboundSchema: z.ZodType<
  Report$Outbound,
  z.ZodTypeDef,
  Report
> = z.object({
  type: Type$outboundSchema.optional(),
});

export function reportToJSON(report: Report): string {
  return JSON.stringify(Report$outboundSchema.parse(report));
}
export function reportFromJSON(
  jsonString: string,
): SafeParseResult<Report, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Report$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Report' from JSON`,
  );
}
