/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ShortURL = {
  fullUrl: string;
  shortUrl: string;
};

/** @internal */
export const ShortURL$inboundSchema: z.ZodType<
  ShortURL,
  z.ZodTypeDef,
  unknown
> = z.object({
  full_url: z.string(),
  short_url: z.string(),
}).transform((v) => {
  return remap$(v, {
    "full_url": "fullUrl",
    "short_url": "shortUrl",
  });
});
/** @internal */
export type ShortURL$Outbound = {
  full_url: string;
  short_url: string;
};

/** @internal */
export const ShortURL$outboundSchema: z.ZodType<
  ShortURL$Outbound,
  z.ZodTypeDef,
  ShortURL
> = z.object({
  fullUrl: z.string(),
  shortUrl: z.string(),
}).transform((v) => {
  return remap$(v, {
    fullUrl: "full_url",
    shortUrl: "short_url",
  });
});

export function shortURLToJSON(shortURL: ShortURL): string {
  return JSON.stringify(ShortURL$outboundSchema.parse(shortURL));
}
export function shortURLFromJSON(
  jsonString: string,
): SafeParseResult<ShortURL, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ShortURL$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ShortURL' from JSON`,
  );
}
