/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type SuggestItemsRequestBody = {
  /**
   * The list of "things" to get suggestions for. One suggestion will be returned for each item in the list.
   */
  items: Array<string>;
  /**
   * The prompt to use for the suggestion. Think of this as the "preamble".
   */
  prompt: string;
};

/** @internal */
export const SuggestItemsRequestBody$inboundSchema: z.ZodType<
  SuggestItemsRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(z.string()),
  prompt: z.string(),
});

/** @internal */
export type SuggestItemsRequestBody$Outbound = {
  items: Array<string>;
  prompt: string;
};

/** @internal */
export const SuggestItemsRequestBody$outboundSchema: z.ZodType<
  SuggestItemsRequestBody$Outbound,
  z.ZodTypeDef,
  SuggestItemsRequestBody
> = z.object({
  items: z.array(z.string()),
  prompt: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SuggestItemsRequestBody$ {
  /** @deprecated use `SuggestItemsRequestBody$inboundSchema` instead. */
  export const inboundSchema = SuggestItemsRequestBody$inboundSchema;
  /** @deprecated use `SuggestItemsRequestBody$outboundSchema` instead. */
  export const outboundSchema = SuggestItemsRequestBody$outboundSchema;
  /** @deprecated use `SuggestItemsRequestBody$Outbound` instead. */
  export type Outbound = SuggestItemsRequestBody$Outbound;
}
