/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Annotations } from "./annotations";
import { Expose, Type } from "class-transformer";

/**
 * V2 descriptor
 */
export class V2Descriptor extends SpeakeasyBase {
    /**
     * Annotations
     */
    @SpeakeasyMetadata()
    @Expose({ name: "annotations" })
    @Type(() => Annotations)
    annotations?: Annotations;

    /**
     * Digest
     */
    @SpeakeasyMetadata()
    @Expose({ name: "digest" })
    digest?: string;

    /**
     * Media type
     */
    @SpeakeasyMetadata()
    @Expose({ name: "mediaType" })
    mediaType?: string;

    /**
     * Size
     */
    @SpeakeasyMetadata()
    @Expose({ name: "size" })
    size?: number;
}
