/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  Organization,
  Organization$inboundSchema,
  Organization$Outbound,
  Organization$outboundSchema,
} from "./organization.js";
import {
  Workspace,
  Workspace$inboundSchema,
  Workspace$Outbound,
  Workspace$outboundSchema,
} from "./workspace.js";

/**
 * A workspace and organization
 */
export type WorkspaceAndOrganization = {
  /**
   * A speakeasy organization
   */
  organization: Organization;
  /**
   * A speakeasy workspace
   */
  workspace: Workspace;
};

/** @internal */
export const WorkspaceAndOrganization$inboundSchema: z.ZodType<
  WorkspaceAndOrganization,
  z.ZodTypeDef,
  unknown
> = z.object({
  organization: Organization$inboundSchema,
  workspace: Workspace$inboundSchema,
});
/** @internal */
export type WorkspaceAndOrganization$Outbound = {
  organization: Organization$Outbound;
  workspace: Workspace$Outbound;
};

/** @internal */
export const WorkspaceAndOrganization$outboundSchema: z.ZodType<
  WorkspaceAndOrganization$Outbound,
  z.ZodTypeDef,
  WorkspaceAndOrganization
> = z.object({
  organization: Organization$outboundSchema,
  workspace: Workspace$outboundSchema,
});

export function workspaceAndOrganizationToJSON(
  workspaceAndOrganization: WorkspaceAndOrganization,
): string {
  return JSON.stringify(
    WorkspaceAndOrganization$outboundSchema.parse(workspaceAndOrganization),
  );
}
export function workspaceAndOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<WorkspaceAndOrganization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WorkspaceAndOrganization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WorkspaceAndOrganization' from JSON`,
  );
}
