/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../sdk/models/errors/httpclienterrors.js";
import * as errors from "../sdk/models/errors/index.js";
import { ResponseValidationError } from "../sdk/models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../sdk/models/errors/sdkvalidationerror.js";
import { SpeakeasyError } from "../sdk/models/errors/speakeasyerror.js";
import * as operations from "../sdk/models/operations/index.js";
import { useSpeakeasyContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  ArtifactsGetManifestQueryData,
  buildArtifactsGetManifestQuery,
  prefetchArtifactsGetManifest,
  queryKeyArtifactsGetManifest,
} from "./artifactsGetManifest.core.js";
export {
  type ArtifactsGetManifestQueryData,
  buildArtifactsGetManifestQuery,
  prefetchArtifactsGetManifest,
  queryKeyArtifactsGetManifest,
};

export type ArtifactsGetManifestQueryError =
  | errors.ErrorT
  | SpeakeasyError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Get manifest for a particular reference
 */
export function useArtifactsGetManifest(
  request: operations.GetManifestRequest,
  options?: QueryHookOptions<
    ArtifactsGetManifestQueryData,
    ArtifactsGetManifestQueryError
  >,
): UseQueryResult<
  ArtifactsGetManifestQueryData,
  ArtifactsGetManifestQueryError
> {
  const client = useSpeakeasyContext();
  return useQuery({
    ...buildArtifactsGetManifestQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * Get manifest for a particular reference
 */
export function useArtifactsGetManifestSuspense(
  request: operations.GetManifestRequest,
  options?: SuspenseQueryHookOptions<
    ArtifactsGetManifestQueryData,
    ArtifactsGetManifestQueryError
  >,
): UseSuspenseQueryResult<
  ArtifactsGetManifestQueryData,
  ArtifactsGetManifestQueryError
> {
  const client = useSpeakeasyContext();
  return useSuspenseQuery({
    ...buildArtifactsGetManifestQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function setArtifactsGetManifestData(
  client: QueryClient,
  queryKeyBase: [
    organizationSlug: string,
    workspaceSlug: string,
    namespaceName: string,
    revisionReference: string,
  ],
  data: ArtifactsGetManifestQueryData,
): ArtifactsGetManifestQueryData | undefined {
  const key = queryKeyArtifactsGetManifest(...queryKeyBase);

  return client.setQueryData<ArtifactsGetManifestQueryData>(key, data);
}

export function invalidateArtifactsGetManifest(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<
    [
      organizationSlug: string,
      workspaceSlug: string,
      namespaceName: string,
      revisionReference: string,
    ]
  >,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: [
      "@speakeasy-api/speakeasy-client-sdk-typescript",
      "Artifacts",
      "getManifest",
      ...queryKeyBase,
    ],
  });
}

export function invalidateAllArtifactsGetManifest(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: [
      "@speakeasy-api/speakeasy-client-sdk-typescript",
      "Artifacts",
      "getManifest",
    ],
  });
}
