/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { SpeakeasyCore } from "../core.js";
import { artifactsGetTags } from "../funcs/artifactsGetTags.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../sdk/models/operations/index.js";
import * as shared from "../sdk/models/shared/index.js";
import { unwrapAsync } from "../sdk/types/fp.js";
export type ArtifactsGetTagsQueryData = shared.GetTagsResponse;

export function prefetchArtifactsGetTags(
  queryClient: QueryClient,
  client$: SpeakeasyCore,
  request: operations.GetTagsRequest,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildArtifactsGetTagsQuery(
      client$,
      request,
      options,
    ),
  });
}

export function buildArtifactsGetTagsQuery(
  client$: SpeakeasyCore,
  request: operations.GetTagsRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<ArtifactsGetTagsQueryData>;
} {
  return {
    queryKey: queryKeyArtifactsGetTags(request.namespaceName),
    queryFn: async function artifactsGetTagsQueryFn(
      ctx,
    ): Promise<ArtifactsGetTagsQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(artifactsGetTags(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyArtifactsGetTags(namespaceName: string): QueryKey {
  return [
    "@speakeasy-api/speakeasy-client-sdk-typescript",
    "Artifacts",
    "getTags",
    namespaceName,
  ];
}
