/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { SpeakeasyCore } from "../core.js";
import { artifactsPreflight } from "../funcs/artifactsPreflight.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as shared from "../sdk/models/shared/index.js";
import { unwrapAsync } from "../sdk/types/fp.js";
import { useSpeakeasyContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type ArtifactsPreflightMutationVariables = {
  request?: shared.PreflightRequest | undefined;
  options?: RequestOptions;
};

export type ArtifactsPreflightMutationData = shared.PreflightToken;

/**
 * Get access token for communicating with OCI distribution endpoints
 */
export function useArtifactsPreflightMutation(
  options?: MutationHookOptions<
    ArtifactsPreflightMutationData,
    Error,
    ArtifactsPreflightMutationVariables
  >,
): UseMutationResult<
  ArtifactsPreflightMutationData,
  Error,
  ArtifactsPreflightMutationVariables
> {
  const client = useSpeakeasyContext();
  return useMutation({
    ...buildArtifactsPreflightMutation(client, options),
    ...options,
  });
}

export function mutationKeyArtifactsPreflight(): MutationKey {
  return [
    "@speakeasy-api/speakeasy-client-sdk-typescript",
    "Artifacts",
    "preflight",
  ];
}

export function buildArtifactsPreflightMutation(
  client$: SpeakeasyCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: ArtifactsPreflightMutationVariables,
  ) => Promise<ArtifactsPreflightMutationData>;
} {
  return {
    mutationKey: mutationKeyArtifactsPreflight(),
    mutationFn: function artifactsPreflightMutationFn({
      request,
      options,
    }): Promise<ArtifactsPreflightMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(artifactsPreflight(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
