/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { SpeakeasyCore } from "../core.js";
import { artifactsGetBlob } from "../funcs/artifactsGetBlob.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../sdk/models/operations/index.js";
import { unwrapAsync } from "../sdk/types/fp.js";
export type ArtifactsGetBlobQueryData = ReadableStream<Uint8Array>;

export function prefetchArtifactsGetBlob(
  queryClient: QueryClient,
  client$: SpeakeasyCore,
  request: operations.GetBlobRequest,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildArtifactsGetBlobQuery(
      client$,
      request,
      options,
    ),
  });
}

export function buildArtifactsGetBlobQuery(
  client$: SpeakeasyCore,
  request: operations.GetBlobRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<ArtifactsGetBlobQueryData>;
} {
  return {
    queryKey: queryKeyArtifactsGetBlob(
      request.organizationSlug,
      request.workspaceSlug,
      request.namespaceName,
      request.digest,
    ),
    queryFn: async function artifactsGetBlobQueryFn(
      ctx,
    ): Promise<ArtifactsGetBlobQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(artifactsGetBlob(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyArtifactsGetBlob(
  organizationSlug: string,
  workspaceSlug: string,
  namespaceName: string,
  digest: string,
): QueryKey {
  return [
    "@speakeasy-api/speakeasy-client-sdk-typescript",
    "Artifacts",
    "getBlob",
    organizationSlug,
    workspaceSlug,
    namespaceName,
    digest,
  ];
}
