/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { SpeakeasyCore } from "../core.js";
import { artifactsSetArchived } from "../funcs/artifactsSetArchived.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../sdk/models/operations/index.js";
import { unwrapAsync } from "../sdk/types/fp.js";
import { useSpeakeasyContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type ArtifactsSetArchivedMutationVariables = {
  request: operations.ArchiveNamespaceRequest;
  options?: RequestOptions;
};

export type ArtifactsSetArchivedMutationData = void;

/**
 * Set whether a namespace is archived
 */
export function useArtifactsSetArchivedMutation(
  options?: MutationHookOptions<
    ArtifactsSetArchivedMutationData,
    Error,
    ArtifactsSetArchivedMutationVariables
  >,
): UseMutationResult<
  ArtifactsSetArchivedMutationData,
  Error,
  ArtifactsSetArchivedMutationVariables
> {
  const client = useSpeakeasyContext();
  return useMutation({
    ...buildArtifactsSetArchivedMutation(client, options),
    ...options,
  });
}

export function mutationKeyArtifactsSetArchived(): MutationKey {
  return [
    "@speakeasy-api/speakeasy-client-sdk-typescript",
    "Artifacts",
    "setArchived",
  ];
}

export function buildArtifactsSetArchivedMutation(
  client$: SpeakeasyCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: ArtifactsSetArchivedMutationVariables,
  ) => Promise<ArtifactsSetArchivedMutationData>;
} {
  return {
    mutationKey: mutationKeyArtifactsSetArchived(),
    mutationFn: function artifactsSetArchivedMutationFn({
      request,
      options,
    }): Promise<ArtifactsSetArchivedMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(artifactsSetArchived(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
