/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  QueryFunctionContext,
  QueryKey,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { SpeakeasyCore } from "../core.js";
import { eventsGetEventsByTarget } from "../funcs/eventsGetEventsByTarget.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../sdk/models/operations/index.js";
import * as shared from "../sdk/models/shared/index.js";
import { unwrapAsync } from "../sdk/types/fp.js";
import { useSpeakeasyContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";

export type EventsGetEventsByTargetQueryData = Array<shared.CliEvent>;

/**
 * Load recent events for a particular workspace
 */
export function useEventsGetEventsByTarget(
  request: operations.GetWorkspaceEventsByTargetRequest,
  options?: QueryHookOptions<EventsGetEventsByTargetQueryData>,
): UseQueryResult<EventsGetEventsByTargetQueryData, Error> {
  const client = useSpeakeasyContext();
  return useQuery({
    ...buildEventsGetEventsByTargetQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * Load recent events for a particular workspace
 */
export function useEventsGetEventsByTargetSuspense(
  request: operations.GetWorkspaceEventsByTargetRequest,
  options?: SuspenseQueryHookOptions<EventsGetEventsByTargetQueryData>,
): UseSuspenseQueryResult<EventsGetEventsByTargetQueryData, Error> {
  const client = useSpeakeasyContext();
  return useSuspenseQuery({
    ...buildEventsGetEventsByTargetQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function prefetchEventsGetEventsByTarget(
  queryClient: QueryClient,
  client$: SpeakeasyCore,
  request: operations.GetWorkspaceEventsByTargetRequest,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildEventsGetEventsByTargetQuery(
      client$,
      request,
    ),
  });
}

export function setEventsGetEventsByTargetData(
  client: QueryClient,
  queryKeyBase: [
    workspaceId: string | undefined,
    targetId: string,
    parameters: { afterCreatedAt?: Date | undefined },
  ],
  data: EventsGetEventsByTargetQueryData,
): EventsGetEventsByTargetQueryData | undefined {
  const key = queryKeyEventsGetEventsByTarget(...queryKeyBase);

  return client.setQueryData<EventsGetEventsByTargetQueryData>(key, data);
}

export function invalidateEventsGetEventsByTarget(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<
    [
      workspaceId: string | undefined,
      targetId: string,
      parameters: { afterCreatedAt?: Date | undefined },
    ]
  >,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: [
      "@speakeasy-api/speakeasy-client-sdk-typescript",
      "Events",
      "getEventsByTarget",
      ...queryKeyBase,
    ],
  });
}

export function invalidateAllEventsGetEventsByTarget(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: [
      "@speakeasy-api/speakeasy-client-sdk-typescript",
      "Events",
      "getEventsByTarget",
    ],
  });
}

export function buildEventsGetEventsByTargetQuery(
  client$: SpeakeasyCore,
  request: operations.GetWorkspaceEventsByTargetRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<EventsGetEventsByTargetQueryData>;
} {
  return {
    queryKey: queryKeyEventsGetEventsByTarget(
      request.workspaceId,
      request.targetId,
      { afterCreatedAt: request.afterCreatedAt },
    ),
    queryFn: async function eventsGetEventsByTargetQueryFn(
      ctx,
    ): Promise<EventsGetEventsByTargetQueryData> {
      const sig = combineSignals(ctx.signal, options?.fetchOptions?.signal);
      const mergedOptions = {
        ...options,
        fetchOptions: { ...options?.fetchOptions, signal: sig },
      };

      return unwrapAsync(eventsGetEventsByTarget(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyEventsGetEventsByTarget(
  workspaceId: string | undefined,
  targetId: string,
  parameters: { afterCreatedAt?: Date | undefined },
): QueryKey {
  return [
    "@speakeasy-api/speakeasy-client-sdk-typescript",
    "Events",
    "getEventsByTarget",
    workspaceId,
    targetId,
    parameters,
  ];
}
