/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { SpeakeasyCore } from "../core.js";
import { githubStorePublishingSecrets } from "../funcs/githubStorePublishingSecrets.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../sdk/models/errors/httpclienterrors.js";
import * as errors from "../sdk/models/errors/index.js";
import { ResponseValidationError } from "../sdk/models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../sdk/models/errors/sdkvalidationerror.js";
import { SpeakeasyError } from "../sdk/models/errors/speakeasyerror.js";
import * as shared from "../sdk/models/shared/index.js";
import { unwrapAsync } from "../sdk/types/fp.js";
import { useSpeakeasyContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type GithubStorePublishingSecretsMutationVariables = {
  request: shared.GithubStorePublishingSecretsRequest;
  options?: RequestOptions;
};

export type GithubStorePublishingSecretsMutationData = void;

export type GithubStorePublishingSecretsMutationError =
  | errors.ErrorT
  | SpeakeasyError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

export function useGithubStorePublishingSecretsMutation(
  options?: MutationHookOptions<
    GithubStorePublishingSecretsMutationData,
    GithubStorePublishingSecretsMutationError,
    GithubStorePublishingSecretsMutationVariables
  >,
): UseMutationResult<
  GithubStorePublishingSecretsMutationData,
  GithubStorePublishingSecretsMutationError,
  GithubStorePublishingSecretsMutationVariables
> {
  const client = useSpeakeasyContext();
  return useMutation({
    ...buildGithubStorePublishingSecretsMutation(client, options),
    ...options,
  });
}

export function mutationKeyGithubStorePublishingSecrets(): MutationKey {
  return [
    "@speakeasy-api/speakeasy-client-sdk-typescript",
    "Github",
    "storePublishingSecrets",
  ];
}

export function buildGithubStorePublishingSecretsMutation(
  client$: SpeakeasyCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: GithubStorePublishingSecretsMutationVariables,
  ) => Promise<GithubStorePublishingSecretsMutationData>;
} {
  return {
    mutationKey: mutationKeyGithubStorePublishingSecrets(),
    mutationFn: function githubStorePublishingSecretsMutationFn({
      request,
      options,
    }): Promise<GithubStorePublishingSecretsMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(githubStorePublishingSecrets(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
