/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  QueryFunctionContext,
  QueryKey,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { SpeakeasyCore } from "../core.js";
import { githubCheckPublishingSecrets } from "../funcs/githubCheckPublishingSecrets.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../sdk/models/operations/index.js";
import * as shared from "../sdk/models/shared/index.js";
import { unwrapAsync } from "../sdk/types/fp.js";
import { useSpeakeasyContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";

export type GithubCheckPublishingSecretsQueryData =
  shared.GithubMissingPublishingSecretsResponse;

export function useGithubCheckPublishingSecrets(
  request: operations.GithubCheckPublishingSecretsRequest,
  options?: QueryHookOptions<GithubCheckPublishingSecretsQueryData>,
): UseQueryResult<GithubCheckPublishingSecretsQueryData, Error> {
  const client = useSpeakeasyContext();
  return useQuery({
    ...buildGithubCheckPublishingSecretsQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function useGithubCheckPublishingSecretsSuspense(
  request: operations.GithubCheckPublishingSecretsRequest,
  options?: SuspenseQueryHookOptions<GithubCheckPublishingSecretsQueryData>,
): UseSuspenseQueryResult<GithubCheckPublishingSecretsQueryData, Error> {
  const client = useSpeakeasyContext();
  return useSuspenseQuery({
    ...buildGithubCheckPublishingSecretsQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function prefetchGithubCheckPublishingSecrets(
  queryClient: QueryClient,
  client$: SpeakeasyCore,
  request: operations.GithubCheckPublishingSecretsRequest,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildGithubCheckPublishingSecretsQuery(
      client$,
      request,
    ),
  });
}

export function setGithubCheckPublishingSecretsData(
  client: QueryClient,
  queryKeyBase: [parameters: { generateGenLockId: string }],
  data: GithubCheckPublishingSecretsQueryData,
): GithubCheckPublishingSecretsQueryData | undefined {
  const key = queryKeyGithubCheckPublishingSecrets(...queryKeyBase);

  return client.setQueryData<GithubCheckPublishingSecretsQueryData>(key, data);
}

export function invalidateGithubCheckPublishingSecrets(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<[parameters: { generateGenLockId: string }]>,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: [
      "@speakeasy-api/speakeasy-client-sdk-typescript",
      "Github",
      "checkPublishingSecrets",
      ...queryKeyBase,
    ],
  });
}

export function invalidateAllGithubCheckPublishingSecrets(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: [
      "@speakeasy-api/speakeasy-client-sdk-typescript",
      "Github",
      "checkPublishingSecrets",
    ],
  });
}

export function buildGithubCheckPublishingSecretsQuery(
  client$: SpeakeasyCore,
  request: operations.GithubCheckPublishingSecretsRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<GithubCheckPublishingSecretsQueryData>;
} {
  return {
    queryKey: queryKeyGithubCheckPublishingSecrets({
      generateGenLockId: request.generateGenLockId,
    }),
    queryFn: async function githubCheckPublishingSecretsQueryFn(
      ctx,
    ): Promise<GithubCheckPublishingSecretsQueryData> {
      const sig = combineSignals(ctx.signal, options?.fetchOptions?.signal);
      const mergedOptions = {
        ...options,
        fetchOptions: { ...options?.fetchOptions, signal: sig },
      };

      return unwrapAsync(githubCheckPublishingSecrets(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyGithubCheckPublishingSecrets(
  parameters: { generateGenLockId: string },
): QueryKey {
  return [
    "@speakeasy-api/speakeasy-client-sdk-typescript",
    "Github",
    "checkPublishingSecrets",
    parameters,
  ];
}
