/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { SpeakeasyCore } from "../core.js";
import { githubConfigureMintlifyRepo } from "../funcs/githubConfigureMintlifyRepo.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as shared from "../sdk/models/shared/index.js";
import { unwrapAsync } from "../sdk/types/fp.js";
import { useSpeakeasyContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type GithubConfigureMintlifyRepoMutationVariables = {
  request: shared.GithubConfigureMintlifyRepoRequest;
  options?: RequestOptions;
};

export type GithubConfigureMintlifyRepoMutationData = void;

export function useGithubConfigureMintlifyRepoMutation(
  options?: MutationHookOptions<
    GithubConfigureMintlifyRepoMutationData,
    Error,
    GithubConfigureMintlifyRepoMutationVariables
  >,
): UseMutationResult<
  GithubConfigureMintlifyRepoMutationData,
  Error,
  GithubConfigureMintlifyRepoMutationVariables
> {
  const client = useSpeakeasyContext();
  return useMutation({
    ...buildGithubConfigureMintlifyRepoMutation(client, options),
    ...options,
  });
}

export function mutationKeyGithubConfigureMintlifyRepo(): MutationKey {
  return [
    "@speakeasy-api/speakeasy-client-sdk-typescript",
    "Github",
    "configureMintlifyRepo",
  ];
}

export function buildGithubConfigureMintlifyRepoMutation(
  client$: SpeakeasyCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: GithubConfigureMintlifyRepoMutationVariables,
  ) => Promise<GithubConfigureMintlifyRepoMutationData>;
} {
  return {
    mutationKey: mutationKeyGithubConfigureMintlifyRepo(),
    mutationFn: function githubConfigureMintlifyRepoMutationFn({
      request,
      options,
    }): Promise<GithubConfigureMintlifyRepoMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(githubConfigureMintlifyRepo(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
