/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../sdk/models/errors/httpclienterrors.js";
import * as errors from "../sdk/models/errors/index.js";
import { ResponseValidationError } from "../sdk/models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../sdk/models/errors/sdkvalidationerror.js";
import { SpeakeasyError } from "../sdk/models/errors/speakeasyerror.js";
import * as operations from "../sdk/models/operations/index.js";
import { useSpeakeasyContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildOrganizationsGetQuery,
  OrganizationsGetQueryData,
  prefetchOrganizationsGet,
  queryKeyOrganizationsGet,
} from "./organizationsGet.core.js";
export {
  buildOrganizationsGetQuery,
  type OrganizationsGetQueryData,
  prefetchOrganizationsGet,
  queryKeyOrganizationsGet,
};

export type OrganizationsGetQueryError =
  | errors.ErrorT
  | SpeakeasyError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Get organization
 *
 * @remarks
 * Get information about a particular organization.
 */
export function useOrganizationsGet(
  request: operations.GetOrganizationRequest,
  options?: QueryHookOptions<
    OrganizationsGetQueryData,
    OrganizationsGetQueryError
  >,
): UseQueryResult<OrganizationsGetQueryData, OrganizationsGetQueryError> {
  const client = useSpeakeasyContext();
  return useQuery({
    ...buildOrganizationsGetQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * Get organization
 *
 * @remarks
 * Get information about a particular organization.
 */
export function useOrganizationsGetSuspense(
  request: operations.GetOrganizationRequest,
  options?: SuspenseQueryHookOptions<
    OrganizationsGetQueryData,
    OrganizationsGetQueryError
  >,
): UseSuspenseQueryResult<
  OrganizationsGetQueryData,
  OrganizationsGetQueryError
> {
  const client = useSpeakeasyContext();
  return useSuspenseQuery({
    ...buildOrganizationsGetQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function setOrganizationsGetData(
  client: QueryClient,
  queryKeyBase: [organizationID: string],
  data: OrganizationsGetQueryData,
): OrganizationsGetQueryData | undefined {
  const key = queryKeyOrganizationsGet(...queryKeyBase);

  return client.setQueryData<OrganizationsGetQueryData>(key, data);
}

export function invalidateOrganizationsGet(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<[organizationID: string]>,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: [
      "@speakeasy-api/speakeasy-client-sdk-typescript",
      "Organizations",
      "get",
      ...queryKeyBase,
    ],
  });
}

export function invalidateAllOrganizationsGet(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: [
      "@speakeasy-api/speakeasy-client-sdk-typescript",
      "Organizations",
      "get",
    ],
  });
}
