/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../sdk/models/errors/httpclienterrors.js";
import * as errors from "../sdk/models/errors/index.js";
import { ResponseValidationError } from "../sdk/models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../sdk/models/errors/sdkvalidationerror.js";
import { SpeakeasyError } from "../sdk/models/errors/speakeasyerror.js";
import { useSpeakeasyContext } from "./_context.js";
import { QueryHookOptions, SuspenseQueryHookOptions } from "./_types.js";
import {
  buildOrganizationsGetSubscriptionQuery,
  OrganizationsGetSubscriptionQueryData,
  prefetchOrganizationsGetSubscription,
  queryKeyOrganizationsGetSubscription,
} from "./organizationsGetSubscription.core.js";
export {
  buildOrganizationsGetSubscriptionQuery,
  type OrganizationsGetSubscriptionQueryData,
  prefetchOrganizationsGetSubscription,
  queryKeyOrganizationsGetSubscription,
};

export type OrganizationsGetSubscriptionQueryError =
  | errors.ErrorT
  | SpeakeasyError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Get organization subscription
 *
 * @remarks
 * Returns the subscription status for the current organization
 */
export function useOrganizationsGetSubscription(
  options?: QueryHookOptions<
    OrganizationsGetSubscriptionQueryData,
    OrganizationsGetSubscriptionQueryError
  >,
): UseQueryResult<
  OrganizationsGetSubscriptionQueryData,
  OrganizationsGetSubscriptionQueryError
> {
  const client = useSpeakeasyContext();
  return useQuery({
    ...buildOrganizationsGetSubscriptionQuery(
      client,
      options,
    ),
    ...options,
  });
}

/**
 * Get organization subscription
 *
 * @remarks
 * Returns the subscription status for the current organization
 */
export function useOrganizationsGetSubscriptionSuspense(
  options?: SuspenseQueryHookOptions<
    OrganizationsGetSubscriptionQueryData,
    OrganizationsGetSubscriptionQueryError
  >,
): UseSuspenseQueryResult<
  OrganizationsGetSubscriptionQueryData,
  OrganizationsGetSubscriptionQueryError
> {
  const client = useSpeakeasyContext();
  return useSuspenseQuery({
    ...buildOrganizationsGetSubscriptionQuery(
      client,
      options,
    ),
    ...options,
  });
}

export function setOrganizationsGetSubscriptionData(
  client: QueryClient,
  data: OrganizationsGetSubscriptionQueryData,
): OrganizationsGetSubscriptionQueryData | undefined {
  const key = queryKeyOrganizationsGetSubscription();

  return client.setQueryData<OrganizationsGetSubscriptionQueryData>(key, data);
}

export function invalidateAllOrganizationsGetSubscription(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: [
      "@speakeasy-api/speakeasy-client-sdk-typescript",
      "Organizations",
      "getSubscription",
    ],
  });
}
