/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { SpeakeasyCore } from "../core.js";
import { organizationsDeactivateLanguage } from "../funcs/organizationsDeactivateLanguage.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../sdk/models/errors/httpclienterrors.js";
import * as errors from "../sdk/models/errors/index.js";
import { ResponseValidationError } from "../sdk/models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../sdk/models/errors/sdkvalidationerror.js";
import { SpeakeasyError } from "../sdk/models/errors/speakeasyerror.js";
import * as operations from "../sdk/models/operations/index.js";
import * as shared from "../sdk/models/shared/index.js";
import { unwrapAsync } from "../sdk/types/fp.js";
import { useSpeakeasyContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type OrganizationsDeactivateLanguageMutationVariables = {
  request: operations.DeactivateLanguageRequest;
  options?: RequestOptions;
};

export type OrganizationsDeactivateLanguageMutationData =
  shared.LanguageActivationResponse;

export type OrganizationsDeactivateLanguageMutationError =
  | errors.ErrorT
  | SpeakeasyError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Deactivate language
 *
 * @remarks
 * Deactivates a language. Subject to 2-week cooldown between deactivations.
 */
export function useOrganizationsDeactivateLanguageMutation(
  options?: MutationHookOptions<
    OrganizationsDeactivateLanguageMutationData,
    OrganizationsDeactivateLanguageMutationError,
    OrganizationsDeactivateLanguageMutationVariables
  >,
): UseMutationResult<
  OrganizationsDeactivateLanguageMutationData,
  OrganizationsDeactivateLanguageMutationError,
  OrganizationsDeactivateLanguageMutationVariables
> {
  const client = useSpeakeasyContext();
  return useMutation({
    ...buildOrganizationsDeactivateLanguageMutation(client, options),
    ...options,
  });
}

export function mutationKeyOrganizationsDeactivateLanguage(): MutationKey {
  return [
    "@speakeasy-api/speakeasy-client-sdk-typescript",
    "Organizations",
    "deactivateLanguage",
  ];
}

export function buildOrganizationsDeactivateLanguageMutation(
  client$: SpeakeasyCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: OrganizationsDeactivateLanguageMutationVariables,
  ) => Promise<OrganizationsDeactivateLanguageMutationData>;
} {
  return {
    mutationKey: mutationKeyOrganizationsDeactivateLanguage(),
    mutationFn: function organizationsDeactivateLanguageMutationFn({
      request,
      options,
    }): Promise<OrganizationsDeactivateLanguageMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(organizationsDeactivateLanguage(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
