/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  QueryFunctionContext,
  QueryKey,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { SpeakeasyCore } from "../core.js";
import { organizationsGetBillingAddOns } from "../funcs/organizationsGetBillingAddOns.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as shared from "../sdk/models/shared/index.js";
import { unwrapAsync } from "../sdk/types/fp.js";
import { useSpeakeasyContext } from "./_context.js";
import { QueryHookOptions, SuspenseQueryHookOptions } from "./_types.js";

export type OrganizationsGetBillingAddOnsQueryData =
  shared.OrganizationBillingAddOnResponse;

/**
 * Get billing add ons
 */
export function useOrganizationsGetBillingAddOns(
  options?: QueryHookOptions<OrganizationsGetBillingAddOnsQueryData>,
): UseQueryResult<OrganizationsGetBillingAddOnsQueryData, Error> {
  const client = useSpeakeasyContext();
  return useQuery({
    ...buildOrganizationsGetBillingAddOnsQuery(
      client,
      options,
    ),
    ...options,
  });
}

/**
 * Get billing add ons
 */
export function useOrganizationsGetBillingAddOnsSuspense(
  options?: SuspenseQueryHookOptions<OrganizationsGetBillingAddOnsQueryData>,
): UseSuspenseQueryResult<OrganizationsGetBillingAddOnsQueryData, Error> {
  const client = useSpeakeasyContext();
  return useSuspenseQuery({
    ...buildOrganizationsGetBillingAddOnsQuery(
      client,
      options,
    ),
    ...options,
  });
}

export function prefetchOrganizationsGetBillingAddOns(
  queryClient: QueryClient,
  client$: SpeakeasyCore,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildOrganizationsGetBillingAddOnsQuery(
      client$,
    ),
  });
}

export function setOrganizationsGetBillingAddOnsData(
  client: QueryClient,
  data: OrganizationsGetBillingAddOnsQueryData,
): OrganizationsGetBillingAddOnsQueryData | undefined {
  const key = queryKeyOrganizationsGetBillingAddOns();

  return client.setQueryData<OrganizationsGetBillingAddOnsQueryData>(key, data);
}

export function invalidateAllOrganizationsGetBillingAddOns(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: [
      "@speakeasy-api/speakeasy-client-sdk-typescript",
      "Organizations",
      "getBillingAddOns",
    ],
  });
}

export function buildOrganizationsGetBillingAddOnsQuery(
  client$: SpeakeasyCore,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<OrganizationsGetBillingAddOnsQueryData>;
} {
  return {
    queryKey: queryKeyOrganizationsGetBillingAddOns(),
    queryFn: async function organizationsGetBillingAddOnsQueryFn(
      ctx,
    ): Promise<OrganizationsGetBillingAddOnsQueryData> {
      const sig = combineSignals(ctx.signal, options?.fetchOptions?.signal);
      const mergedOptions = {
        ...options,
        fetchOptions: { ...options?.fetchOptions, signal: sig },
      };

      return unwrapAsync(organizationsGetBillingAddOns(
        client$,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyOrganizationsGetBillingAddOns(): QueryKey {
  return [
    "@speakeasy-api/speakeasy-client-sdk-typescript",
    "Organizations",
    "getBillingAddOns",
  ];
}
