/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { SpeakeasyCore } from "../core.js";
import { organizationsHandleCheckoutCallback } from "../funcs/organizationsHandleCheckoutCallback.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../sdk/models/operations/index.js";
import { unwrapAsync } from "../sdk/types/fp.js";
export type OrganizationsHandleCheckoutCallbackQueryData =
  | operations.HandleCheckoutCallbackResponse
  | undefined;

export function prefetchOrganizationsHandleCheckoutCallback(
  queryClient: QueryClient,
  client$: SpeakeasyCore,
  request: operations.HandleCheckoutCallbackRequest,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildOrganizationsHandleCheckoutCallbackQuery(
      client$,
      request,
      options,
    ),
  });
}

export function buildOrganizationsHandleCheckoutCallbackQuery(
  client$: SpeakeasyCore,
  request: operations.HandleCheckoutCallbackRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<OrganizationsHandleCheckoutCallbackQueryData>;
} {
  return {
    queryKey: queryKeyOrganizationsHandleCheckoutCallback({
      sessionId: request.sessionId,
    }),
    queryFn: async function organizationsHandleCheckoutCallbackQueryFn(
      ctx,
    ): Promise<OrganizationsHandleCheckoutCallbackQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(organizationsHandleCheckoutCallback(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyOrganizationsHandleCheckoutCallback(
  parameters: { sessionId: string },
): QueryKey {
  return [
    "@speakeasy-api/speakeasy-client-sdk-typescript",
    "Organizations",
    "handleCheckoutCallback",
    parameters,
  ];
}
