/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../sdk/models/errors/httpclienterrors.js";
import * as errors from "../sdk/models/errors/index.js";
import { ResponseValidationError } from "../sdk/models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../sdk/models/errors/sdkvalidationerror.js";
import { SpeakeasyError } from "../sdk/models/errors/speakeasyerror.js";
import { useSpeakeasyContext } from "./_context.js";
import { QueryHookOptions, SuspenseQueryHookOptions } from "./_types.js";
import {
  buildOrganizationsGetBusinessTierPricesQuery,
  OrganizationsGetBusinessTierPricesQueryData,
  prefetchOrganizationsGetBusinessTierPrices,
  queryKeyOrganizationsGetBusinessTierPrices,
} from "./organizationsGetBusinessTierPrices.core.js";
export {
  buildOrganizationsGetBusinessTierPricesQuery,
  type OrganizationsGetBusinessTierPricesQueryData,
  prefetchOrganizationsGetBusinessTierPrices,
  queryKeyOrganizationsGetBusinessTierPrices,
};

export type OrganizationsGetBusinessTierPricesQueryError =
  | errors.ErrorT
  | SpeakeasyError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Get business tier prices
 *
 * @remarks
 * Returns both monthly and annual business tier prices from Stripe
 */
export function useOrganizationsGetBusinessTierPrices(
  options?: QueryHookOptions<
    OrganizationsGetBusinessTierPricesQueryData,
    OrganizationsGetBusinessTierPricesQueryError
  >,
): UseQueryResult<
  OrganizationsGetBusinessTierPricesQueryData,
  OrganizationsGetBusinessTierPricesQueryError
> {
  const client = useSpeakeasyContext();
  return useQuery({
    ...buildOrganizationsGetBusinessTierPricesQuery(
      client,
      options,
    ),
    ...options,
  });
}

/**
 * Get business tier prices
 *
 * @remarks
 * Returns both monthly and annual business tier prices from Stripe
 */
export function useOrganizationsGetBusinessTierPricesSuspense(
  options?: SuspenseQueryHookOptions<
    OrganizationsGetBusinessTierPricesQueryData,
    OrganizationsGetBusinessTierPricesQueryError
  >,
): UseSuspenseQueryResult<
  OrganizationsGetBusinessTierPricesQueryData,
  OrganizationsGetBusinessTierPricesQueryError
> {
  const client = useSpeakeasyContext();
  return useSuspenseQuery({
    ...buildOrganizationsGetBusinessTierPricesQuery(
      client,
      options,
    ),
    ...options,
  });
}

export function setOrganizationsGetBusinessTierPricesData(
  client: QueryClient,
  data: OrganizationsGetBusinessTierPricesQueryData,
): OrganizationsGetBusinessTierPricesQueryData | undefined {
  const key = queryKeyOrganizationsGetBusinessTierPrices();

  return client.setQueryData<OrganizationsGetBusinessTierPricesQueryData>(
    key,
    data,
  );
}

export function invalidateAllOrganizationsGetBusinessTierPrices(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: [
      "@speakeasy-api/speakeasy-client-sdk-typescript",
      "Organizations",
      "getBusinessTierPrices",
    ],
  });
}
