/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { SpeakeasyCore } from "../core.js";
import { organizationsGet } from "../funcs/organizationsGet.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../sdk/models/operations/index.js";
import * as shared from "../sdk/models/shared/index.js";
import { unwrapAsync } from "../sdk/types/fp.js";
export type OrganizationsGetQueryData = shared.Organization;

export function prefetchOrganizationsGet(
  queryClient: QueryClient,
  client$: SpeakeasyCore,
  request: operations.GetOrganizationRequest,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildOrganizationsGetQuery(
      client$,
      request,
      options,
    ),
  });
}

export function buildOrganizationsGetQuery(
  client$: SpeakeasyCore,
  request: operations.GetOrganizationRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<OrganizationsGetQueryData>;
} {
  return {
    queryKey: queryKeyOrganizationsGet(request.organizationID),
    queryFn: async function organizationsGetQueryFn(
      ctx,
    ): Promise<OrganizationsGetQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(organizationsGet(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyOrganizationsGet(organizationID: string): QueryKey {
  return [
    "@speakeasy-api/speakeasy-client-sdk-typescript",
    "Organizations",
    "get",
    organizationID,
  ];
}
