/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  QueryFunctionContext,
  QueryKey,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { SpeakeasyCore } from "../core.js";
import { publishingTokensResolveMetadata } from "../funcs/publishingTokensResolveMetadata.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../sdk/models/operations/index.js";
import { unwrapAsync } from "../sdk/types/fp.js";
import { useSpeakeasyContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";

export type PublishingTokensResolveMetadataQueryData =
  operations.GetPublishingTokenPublicMetadataResponseBody;

/**
 * Get metadata about the token
 *
 * @remarks
 * Get information about a particular publishing token.
 */
export function usePublishingTokensResolveMetadata(
  request: operations.GetPublishingTokenPublicMetadataRequest,
  options?: QueryHookOptions<PublishingTokensResolveMetadataQueryData>,
): UseQueryResult<PublishingTokensResolveMetadataQueryData, Error> {
  const client = useSpeakeasyContext();
  return useQuery({
    ...buildPublishingTokensResolveMetadataQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * Get metadata about the token
 *
 * @remarks
 * Get information about a particular publishing token.
 */
export function usePublishingTokensResolveMetadataSuspense(
  request: operations.GetPublishingTokenPublicMetadataRequest,
  options?: SuspenseQueryHookOptions<PublishingTokensResolveMetadataQueryData>,
): UseSuspenseQueryResult<PublishingTokensResolveMetadataQueryData, Error> {
  const client = useSpeakeasyContext();
  return useSuspenseQuery({
    ...buildPublishingTokensResolveMetadataQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function prefetchPublishingTokensResolveMetadata(
  queryClient: QueryClient,
  client$: SpeakeasyCore,
  request: operations.GetPublishingTokenPublicMetadataRequest,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildPublishingTokensResolveMetadataQuery(
      client$,
      request,
    ),
  });
}

export function setPublishingTokensResolveMetadataData(
  client: QueryClient,
  queryKeyBase: [tokenID: string],
  data: PublishingTokensResolveMetadataQueryData,
): PublishingTokensResolveMetadataQueryData | undefined {
  const key = queryKeyPublishingTokensResolveMetadata(...queryKeyBase);

  return client.setQueryData<PublishingTokensResolveMetadataQueryData>(
    key,
    data,
  );
}

export function invalidatePublishingTokensResolveMetadata(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<[tokenID: string]>,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: [
      "@speakeasy-api/speakeasy-client-sdk-typescript",
      "PublishingTokens",
      "resolveMetadata",
      ...queryKeyBase,
    ],
  });
}

export function invalidateAllPublishingTokensResolveMetadata(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: [
      "@speakeasy-api/speakeasy-client-sdk-typescript",
      "PublishingTokens",
      "resolveMetadata",
    ],
  });
}

export function buildPublishingTokensResolveMetadataQuery(
  client$: SpeakeasyCore,
  request: operations.GetPublishingTokenPublicMetadataRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<PublishingTokensResolveMetadataQueryData>;
} {
  return {
    queryKey: queryKeyPublishingTokensResolveMetadata(request.tokenID),
    queryFn: async function publishingTokensResolveMetadataQueryFn(
      ctx,
    ): Promise<PublishingTokensResolveMetadataQueryData> {
      const sig = combineSignals(ctx.signal, options?.fetchOptions?.signal);
      const mergedOptions = {
        ...options,
        fetchOptions: { ...options?.fetchOptions, signal: sig },
      };

      return unwrapAsync(publishingTokensResolveMetadata(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyPublishingTokensResolveMetadata(
  tokenID: string,
): QueryKey {
  return [
    "@speakeasy-api/speakeasy-client-sdk-typescript",
    "PublishingTokens",
    "resolveMetadata",
    tokenID,
  ];
}
