/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  QueryFunctionContext,
  QueryKey,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { SpeakeasyCore } from "../core.js";
import { publishingTokensList } from "../funcs/publishingTokensList.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as shared from "../sdk/models/shared/index.js";
import { unwrapAsync } from "../sdk/types/fp.js";
import { useSpeakeasyContext } from "./_context.js";
import { QueryHookOptions, SuspenseQueryHookOptions } from "./_types.js";

export type PublishingTokensListQueryData = Array<shared.PublishingToken>;

/**
 * Get publishing tokens for a workspace
 *
 * @remarks
 * Returns a publishing token for the current workspace
 */
export function usePublishingTokensList(
  options?: QueryHookOptions<PublishingTokensListQueryData>,
): UseQueryResult<PublishingTokensListQueryData, Error> {
  const client = useSpeakeasyContext();
  return useQuery({
    ...buildPublishingTokensListQuery(
      client,
      options,
    ),
    ...options,
  });
}

/**
 * Get publishing tokens for a workspace
 *
 * @remarks
 * Returns a publishing token for the current workspace
 */
export function usePublishingTokensListSuspense(
  options?: SuspenseQueryHookOptions<PublishingTokensListQueryData>,
): UseSuspenseQueryResult<PublishingTokensListQueryData, Error> {
  const client = useSpeakeasyContext();
  return useSuspenseQuery({
    ...buildPublishingTokensListQuery(
      client,
      options,
    ),
    ...options,
  });
}

export function prefetchPublishingTokensList(
  queryClient: QueryClient,
  client$: SpeakeasyCore,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildPublishingTokensListQuery(
      client$,
    ),
  });
}

export function setPublishingTokensListData(
  client: QueryClient,
  data: PublishingTokensListQueryData,
): PublishingTokensListQueryData | undefined {
  const key = queryKeyPublishingTokensList();

  return client.setQueryData<PublishingTokensListQueryData>(key, data);
}

export function invalidateAllPublishingTokensList(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: [
      "@speakeasy-api/speakeasy-client-sdk-typescript",
      "PublishingTokens",
      "list",
    ],
  });
}

export function buildPublishingTokensListQuery(
  client$: SpeakeasyCore,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<PublishingTokensListQueryData>;
} {
  return {
    queryKey: queryKeyPublishingTokensList(),
    queryFn: async function publishingTokensListQueryFn(
      ctx,
    ): Promise<PublishingTokensListQueryData> {
      const sig = combineSignals(ctx.signal, options?.fetchOptions?.signal);
      const mergedOptions = {
        ...options,
        fetchOptions: { ...options?.fetchOptions, signal: sig },
      };

      return unwrapAsync(publishingTokensList(
        client$,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyPublishingTokensList(): QueryKey {
  return [
    "@speakeasy-api/speakeasy-client-sdk-typescript",
    "PublishingTokens",
    "list",
  ];
}
