/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { SpeakeasyCore } from "../core.js";
import { reportsUploadReport } from "../funcs/reportsUploadReport.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../sdk/models/errors/httpclienterrors.js";
import { ResponseValidationError } from "../sdk/models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../sdk/models/errors/sdkvalidationerror.js";
import { SpeakeasyError } from "../sdk/models/errors/speakeasyerror.js";
import * as operations from "../sdk/models/operations/index.js";
import { unwrapAsync } from "../sdk/types/fp.js";
import { useSpeakeasyContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type ReportsUploadReportMutationVariables = {
  request: operations.UploadReportRequestBody;
  options?: RequestOptions;
};

export type ReportsUploadReportMutationData =
  operations.UploadReportUploadedReport;

export type ReportsUploadReportMutationError =
  | SpeakeasyError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Upload a report.
 */
export function useReportsUploadReportMutation(
  options?: MutationHookOptions<
    ReportsUploadReportMutationData,
    ReportsUploadReportMutationError,
    ReportsUploadReportMutationVariables
  >,
): UseMutationResult<
  ReportsUploadReportMutationData,
  ReportsUploadReportMutationError,
  ReportsUploadReportMutationVariables
> {
  const client = useSpeakeasyContext();
  return useMutation({
    ...buildReportsUploadReportMutation(client, options),
    ...options,
  });
}

export function mutationKeyReportsUploadReport(): MutationKey {
  return [
    "@speakeasy-api/speakeasy-client-sdk-typescript",
    "Reports",
    "uploadReport",
  ];
}

export function buildReportsUploadReportMutation(
  client$: SpeakeasyCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: ReportsUploadReportMutationVariables,
  ) => Promise<ReportsUploadReportMutationData>;
} {
  return {
    mutationKey: mutationKeyReportsUploadReport(),
    mutationFn: function reportsUploadReportMutationFn({
      request,
      options,
    }): Promise<ReportsUploadReportMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(reportsUploadReport(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
