/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { SpeakeasyCore } from "../core.js";
import { workspacesGrantAccess } from "../funcs/workspacesGrantAccess.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../sdk/models/operations/index.js";
import * as shared from "../sdk/models/shared/index.js";
import { unwrapAsync } from "../sdk/types/fp.js";
import { useSpeakeasyContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type WorkspacesGrantAccessMutationVariables = {
  request: operations.GrantUserAccessToWorkspaceRequest;
  options?: RequestOptions;
};

export type WorkspacesGrantAccessMutationData = shared.WorkspaceInviteResponse;

/**
 * Grant a user access to a particular workspace
 */
export function useWorkspacesGrantAccessMutation(
  options?: MutationHookOptions<
    WorkspacesGrantAccessMutationData,
    Error,
    WorkspacesGrantAccessMutationVariables
  >,
): UseMutationResult<
  WorkspacesGrantAccessMutationData,
  Error,
  WorkspacesGrantAccessMutationVariables
> {
  const client = useSpeakeasyContext();
  return useMutation({
    ...buildWorkspacesGrantAccessMutation(client, options),
    ...options,
  });
}

export function mutationKeyWorkspacesGrantAccess(): MutationKey {
  return [
    "@speakeasy-api/speakeasy-client-sdk-typescript",
    "Workspaces",
    "grantAccess",
  ];
}

export function buildWorkspacesGrantAccessMutation(
  client$: SpeakeasyCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: WorkspacesGrantAccessMutationVariables,
  ) => Promise<WorkspacesGrantAccessMutationData>;
} {
  return {
    mutationKey: mutationKeyWorkspacesGrantAccess(),
    mutationFn: function workspacesGrantAccessMutationFn({
      request,
      options,
    }): Promise<WorkspacesGrantAccessMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(workspacesGrantAccess(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
