/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../sdk/models/errors/httpclienterrors.js";
import * as errors from "../sdk/models/errors/index.js";
import { ResponseValidationError } from "../sdk/models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../sdk/models/errors/sdkvalidationerror.js";
import { SpeakeasyError } from "../sdk/models/errors/speakeasyerror.js";
import * as operations from "../sdk/models/operations/index.js";
import { useSpeakeasyContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildWorkspacesGetByIDQuery,
  prefetchWorkspacesGetByID,
  queryKeyWorkspacesGetByID,
  WorkspacesGetByIDQueryData,
} from "./workspacesGetByID.core.js";
export {
  buildWorkspacesGetByIDQuery,
  prefetchWorkspacesGetByID,
  queryKeyWorkspacesGetByID,
  type WorkspacesGetByIDQueryData,
};

export type WorkspacesGetByIDQueryError =
  | errors.ErrorT
  | SpeakeasyError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Get workspace
 *
 * @remarks
 * Get information about a particular workspace.
 */
export function useWorkspacesGetByID(
  request: operations.GetWorkspaceRequest,
  options?: QueryHookOptions<
    WorkspacesGetByIDQueryData,
    WorkspacesGetByIDQueryError
  >,
): UseQueryResult<WorkspacesGetByIDQueryData, WorkspacesGetByIDQueryError> {
  const client = useSpeakeasyContext();
  return useQuery({
    ...buildWorkspacesGetByIDQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * Get workspace
 *
 * @remarks
 * Get information about a particular workspace.
 */
export function useWorkspacesGetByIDSuspense(
  request: operations.GetWorkspaceRequest,
  options?: SuspenseQueryHookOptions<
    WorkspacesGetByIDQueryData,
    WorkspacesGetByIDQueryError
  >,
): UseSuspenseQueryResult<
  WorkspacesGetByIDQueryData,
  WorkspacesGetByIDQueryError
> {
  const client = useSpeakeasyContext();
  return useSuspenseQuery({
    ...buildWorkspacesGetByIDQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function setWorkspacesGetByIDData(
  client: QueryClient,
  queryKeyBase: [workspaceId: string | undefined],
  data: WorkspacesGetByIDQueryData,
): WorkspacesGetByIDQueryData | undefined {
  const key = queryKeyWorkspacesGetByID(...queryKeyBase);

  return client.setQueryData<WorkspacesGetByIDQueryData>(key, data);
}

export function invalidateWorkspacesGetByID(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<[workspaceId: string | undefined]>,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: [
      "@speakeasy-api/speakeasy-client-sdk-typescript",
      "Workspaces",
      "getByID",
      ...queryKeyBase,
    ],
  });
}

export function invalidateAllWorkspacesGetByID(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: [
      "@speakeasy-api/speakeasy-client-sdk-typescript",
      "Workspaces",
      "getByID",
    ],
  });
}
