/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { SpeakeasyCore } from "../core.js";
import { workspacesDeleteToken } from "../funcs/workspacesDeleteToken.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../sdk/models/operations/index.js";
import { unwrapAsync } from "../sdk/types/fp.js";
import { useSpeakeasyContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type WorkspacesDeleteTokenMutationVariables = {
  request: operations.DeleteWorkspaceTokenRequest;
  options?: RequestOptions;
};

export type WorkspacesDeleteTokenMutationData = void;

/**
 * Delete a token for a particular workspace
 */
export function useWorkspacesDeleteTokenMutation(
  options?: MutationHookOptions<
    WorkspacesDeleteTokenMutationData,
    Error,
    WorkspacesDeleteTokenMutationVariables
  >,
): UseMutationResult<
  WorkspacesDeleteTokenMutationData,
  Error,
  WorkspacesDeleteTokenMutationVariables
> {
  const client = useSpeakeasyContext();
  return useMutation({
    ...buildWorkspacesDeleteTokenMutation(client, options),
    ...options,
  });
}

export function mutationKeyWorkspacesDeleteToken(): MutationKey {
  return [
    "@speakeasy-api/speakeasy-client-sdk-typescript",
    "Workspaces",
    "deleteToken",
  ];
}

export function buildWorkspacesDeleteTokenMutation(
  client$: SpeakeasyCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: WorkspacesDeleteTokenMutationVariables,
  ) => Promise<WorkspacesDeleteTokenMutationData>;
} {
  return {
    mutationKey: mutationKeyWorkspacesDeleteToken(),
    mutationFn: function workspacesDeleteTokenMutationFn({
      request,
      options,
    }): Promise<WorkspacesDeleteTokenMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(workspacesDeleteToken(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
