/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { SpeakeasyCore } from "../core.js";
import { workspacesDeleteToken } from "../funcs/workspacesDeleteToken.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../sdk/models/errors/httpclienterrors.js";
import * as errors from "../sdk/models/errors/index.js";
import { ResponseValidationError } from "../sdk/models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../sdk/models/errors/sdkvalidationerror.js";
import { SpeakeasyError } from "../sdk/models/errors/speakeasyerror.js";
import * as operations from "../sdk/models/operations/index.js";
import { unwrapAsync } from "../sdk/types/fp.js";
import { useSpeakeasyContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type WorkspacesDeleteTokenMutationVariables = {
  request: operations.DeleteWorkspaceTokenRequest;
  options?: RequestOptions;
};

export type WorkspacesDeleteTokenMutationData = void;

export type WorkspacesDeleteTokenMutationError =
  | errors.ErrorT
  | SpeakeasyError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Delete a token for a particular workspace
 */
export function useWorkspacesDeleteTokenMutation(
  options?: MutationHookOptions<
    WorkspacesDeleteTokenMutationData,
    WorkspacesDeleteTokenMutationError,
    WorkspacesDeleteTokenMutationVariables
  >,
): UseMutationResult<
  WorkspacesDeleteTokenMutationData,
  WorkspacesDeleteTokenMutationError,
  WorkspacesDeleteTokenMutationVariables
> {
  const client = useSpeakeasyContext();
  return useMutation({
    ...buildWorkspacesDeleteTokenMutation(client, options),
    ...options,
  });
}

export function mutationKeyWorkspacesDeleteToken(): MutationKey {
  return [
    "@speakeasy-api/speakeasy-client-sdk-typescript",
    "Workspaces",
    "deleteToken",
  ];
}

export function buildWorkspacesDeleteTokenMutation(
  client$: SpeakeasyCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: WorkspacesDeleteTokenMutationVariables,
  ) => Promise<WorkspacesDeleteTokenMutationData>;
} {
  return {
    mutationKey: mutationKeyWorkspacesDeleteToken(),
    mutationFn: function workspacesDeleteTokenMutationFn({
      request,
      options,
    }): Promise<WorkspacesDeleteTokenMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(workspacesDeleteToken(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
