/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { SpeakeasyCore } from "../core.js";
import { encodeSimple as encodeSimple$ } from "../lib/encodings.js";
import * as m$ from "../lib/matchers.js";
import * as schemas$ from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import {
    ConnectionError,
    InvalidRequestError,
    RequestAbortedError,
    RequestTimeoutError,
    UnexpectedClientError,
} from "../sdk/models/errors/httpclienterrors.js";
import { SDKError } from "../sdk/models/errors/sdkerror.js";
import { SDKValidationError } from "../sdk/models/errors/sdkvalidationerror.js";
import * as operations from "../sdk/models/operations/index.js";
import { Result } from "../sdk/types/fp.js";

export enum GetManifestAcceptEnum {
    applicationJson = "application/json",
    applicationVndOciImageManifestV1PlusJson = "application/vnd.oci.image.manifest.v1+json",
}

/**
 * Get manifest for a particular reference
 */
export async function artifactsGetManifest(
    client$: SpeakeasyCore,
    request: operations.GetManifestRequest,
    options?: RequestOptions & { acceptHeaderOverride?: GetManifestAcceptEnum }
): Promise<
    Result<
        operations.GetManifestResponse,
        | SDKError
        | SDKValidationError
        | UnexpectedClientError
        | InvalidRequestError
        | RequestAbortedError
        | RequestTimeoutError
        | ConnectionError
    >
> {
    const input$ = request;

    const parsed$ = schemas$.safeParse(
        input$,
        (value$) => operations.GetManifestRequest$outboundSchema.parse(value$),
        "Input validation failed"
    );
    if (!parsed$.ok) {
        return parsed$;
    }
    const payload$ = parsed$.value;
    const body$ = null;

    const pathParams$ = {
        namespace_name: encodeSimple$("namespace_name", payload$.namespace_name, {
            explode: false,
            charEncoding: "percent",
        }),
        organization_slug: encodeSimple$("organization_slug", payload$.organization_slug, {
            explode: false,
            charEncoding: "percent",
        }),
        revision_reference: encodeSimple$("revision_reference", payload$.revision_reference, {
            explode: false,
            charEncoding: "percent",
        }),
        workspace_slug: encodeSimple$("workspace_slug", payload$.workspace_slug, {
            explode: false,
            charEncoding: "percent",
        }),
    };

    const path$ = pathToFunc(
        "/v1/oci/v2/{organization_slug}/{workspace_slug}/{namespace_name}/manifests/{revision_reference}"
    )(pathParams$);

    const headers$ = new Headers({
        Accept:
            options?.acceptHeaderOverride ||
            "application/json;q=1, application/vnd.oci.image.manifest.v1+json;q=0",
    });

    const security$ = await extractSecurity(client$.options$.security);
    const context = {
        operationID: "getManifest",
        oAuth2Scopes: [],
        securitySource: client$.options$.security,
    };
    const securitySettings$ = resolveGlobalSecurity(security$);

    const requestRes = client$.createRequest$(
        context,
        {
            security: securitySettings$,
            method: "GET",
            path: path$,
            headers: headers$,
            body: body$,
            timeoutMs: options?.timeoutMs || client$.options$.timeoutMs || -1,
        },
        options
    );
    if (!requestRes.ok) {
        return requestRes;
    }
    const request$ = requestRes.value;

    const doResult = await client$.do$(request$, {
        context,
        errorCodes: [],
        retryConfig: options?.retries || client$.options$.retryConfig,
        retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
    });
    if (!doResult.ok) {
        return doResult;
    }
    const response = doResult.value;

    const [result$] = await m$.match<
        operations.GetManifestResponse,
        | SDKError
        | SDKValidationError
        | UnexpectedClientError
        | InvalidRequestError
        | RequestAbortedError
        | RequestTimeoutError
        | ConnectionError
    >(
        m$.json(200, operations.GetManifestResponse$inboundSchema, {
            ctype: "application/vnd.oci.image.manifest.v1+json",
        }),
        m$.json("default", operations.GetManifestResponse$inboundSchema)
    )(response);
    if (!result$.ok) {
        return result$;
    }

    return result$;
}
