/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Archived status
 */
export type ArchiveNamespaceRequestBody = {
  archived?: boolean | undefined;
};

export type ArchiveNamespaceRequest = {
  namespaceName: string;
  /**
   * Archived status
   */
  requestBody?: ArchiveNamespaceRequestBody | undefined;
};

/** @internal */
export const ArchiveNamespaceRequestBody$inboundSchema: z.ZodType<
  ArchiveNamespaceRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  archived: z.boolean().default(true),
});
/** @internal */
export type ArchiveNamespaceRequestBody$Outbound = {
  archived: boolean;
};

/** @internal */
export const ArchiveNamespaceRequestBody$outboundSchema: z.ZodType<
  ArchiveNamespaceRequestBody$Outbound,
  z.ZodTypeDef,
  ArchiveNamespaceRequestBody
> = z.object({
  archived: z.boolean().default(true),
});

export function archiveNamespaceRequestBodyToJSON(
  archiveNamespaceRequestBody: ArchiveNamespaceRequestBody,
): string {
  return JSON.stringify(
    ArchiveNamespaceRequestBody$outboundSchema.parse(
      archiveNamespaceRequestBody,
    ),
  );
}
export function archiveNamespaceRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<ArchiveNamespaceRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ArchiveNamespaceRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ArchiveNamespaceRequestBody' from JSON`,
  );
}

/** @internal */
export const ArchiveNamespaceRequest$inboundSchema: z.ZodType<
  ArchiveNamespaceRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  namespace_name: z.string(),
  RequestBody: z.lazy(() => ArchiveNamespaceRequestBody$inboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "namespace_name": "namespaceName",
    "RequestBody": "requestBody",
  });
});
/** @internal */
export type ArchiveNamespaceRequest$Outbound = {
  namespace_name: string;
  RequestBody?: ArchiveNamespaceRequestBody$Outbound | undefined;
};

/** @internal */
export const ArchiveNamespaceRequest$outboundSchema: z.ZodType<
  ArchiveNamespaceRequest$Outbound,
  z.ZodTypeDef,
  ArchiveNamespaceRequest
> = z.object({
  namespaceName: z.string(),
  requestBody: z.lazy(() => ArchiveNamespaceRequestBody$outboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    namespaceName: "namespace_name",
    requestBody: "RequestBody",
  });
});

export function archiveNamespaceRequestToJSON(
  archiveNamespaceRequest: ArchiveNamespaceRequest,
): string {
  return JSON.stringify(
    ArchiveNamespaceRequest$outboundSchema.parse(archiveNamespaceRequest),
  );
}
export function archiveNamespaceRequestFromJSON(
  jsonString: string,
): SafeParseResult<ArchiveNamespaceRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ArchiveNamespaceRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ArchiveNamespaceRequest' from JSON`,
  );
}
