/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../../lib/primitives.js";
import * as shared from "../shared/index.js";

export type CreateSubscriptionRequest = {
  /**
   * The workspace ID
   */
  workspaceId: string;
  /**
   * The subscription to create
   */
  subscription: shared.Subscription;
};

/** @internal */
export const CreateSubscriptionRequest$inboundSchema: z.ZodType<
  CreateSubscriptionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  workspace_id: z.string(),
  Subscription: shared.Subscription$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "workspace_id": "workspaceId",
    "Subscription": "subscription",
  });
});

/** @internal */
export type CreateSubscriptionRequest$Outbound = {
  workspace_id: string;
  Subscription: shared.Subscription$Outbound;
};

/** @internal */
export const CreateSubscriptionRequest$outboundSchema: z.ZodType<
  CreateSubscriptionRequest$Outbound,
  z.ZodTypeDef,
  CreateSubscriptionRequest
> = z.object({
  workspaceId: z.string(),
  subscription: shared.Subscription$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    workspaceId: "workspace_id",
    subscription: "Subscription",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateSubscriptionRequest$ {
  /** @deprecated use `CreateSubscriptionRequest$inboundSchema` instead. */
  export const inboundSchema = CreateSubscriptionRequest$inboundSchema;
  /** @deprecated use `CreateSubscriptionRequest$outboundSchema` instead. */
  export const outboundSchema = CreateSubscriptionRequest$outboundSchema;
  /** @deprecated use `CreateSubscriptionRequest$Outbound` instead. */
  export type Outbound = CreateSubscriptionRequest$Outbound;
}
