/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeletePublishingTokenRequest = {
  /**
   * Unique identifier of the publishing token.
   */
  tokenID: string;
};

/** @internal */
export const DeletePublishingTokenRequest$inboundSchema: z.ZodType<
  DeletePublishingTokenRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  tokenID: z.string(),
});
/** @internal */
export type DeletePublishingTokenRequest$Outbound = {
  tokenID: string;
};

/** @internal */
export const DeletePublishingTokenRequest$outboundSchema: z.ZodType<
  DeletePublishingTokenRequest$Outbound,
  z.ZodTypeDef,
  DeletePublishingTokenRequest
> = z.object({
  tokenID: z.string(),
});

export function deletePublishingTokenRequestToJSON(
  deletePublishingTokenRequest: DeletePublishingTokenRequest,
): string {
  return JSON.stringify(
    DeletePublishingTokenRequest$outboundSchema.parse(
      deletePublishingTokenRequest,
    ),
  );
}
export function deletePublishingTokenRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeletePublishingTokenRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeletePublishingTokenRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeletePublishingTokenRequest' from JSON`,
  );
}
