/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../../lib/primitives.js";

export type DeleteWorkspaceTokenRequest = {
  /**
   * Unique identifier of the workspace.
   */
  workspaceId: string;
  /**
   * Unique identifier of the token.
   */
  tokenID: string;
};

/** @internal */
export const DeleteWorkspaceTokenRequest$inboundSchema: z.ZodType<
  DeleteWorkspaceTokenRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  workspace_id: z.string(),
  tokenID: z.string(),
}).transform((v) => {
  return remap$(v, {
    "workspace_id": "workspaceId",
  });
});

/** @internal */
export type DeleteWorkspaceTokenRequest$Outbound = {
  workspace_id: string;
  tokenID: string;
};

/** @internal */
export const DeleteWorkspaceTokenRequest$outboundSchema: z.ZodType<
  DeleteWorkspaceTokenRequest$Outbound,
  z.ZodTypeDef,
  DeleteWorkspaceTokenRequest
> = z.object({
  workspaceId: z.string(),
  tokenID: z.string(),
}).transform((v) => {
  return remap$(v, {
    workspaceId: "workspace_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteWorkspaceTokenRequest$ {
  /** @deprecated use `DeleteWorkspaceTokenRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteWorkspaceTokenRequest$inboundSchema;
  /** @deprecated use `DeleteWorkspaceTokenRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteWorkspaceTokenRequest$outboundSchema;
  /** @deprecated use `DeleteWorkspaceTokenRequest$Outbound` instead. */
  export type Outbound = DeleteWorkspaceTokenRequest$Outbound;
}
