/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type GetPublishingTokenTargetByIDRequest = {
  /**
   * Unique identifier of the publishing token.
   */
  tokenID: string;
};

/**
 * OK
 */
export type GetPublishingTokenTargetByIDResponseBody = {};

export type GetPublishingTokenTargetByIDResponse =
  | GetPublishingTokenTargetByIDResponseBody
  | shared.ErrorT;

/** @internal */
export const GetPublishingTokenTargetByIDRequest$inboundSchema: z.ZodType<
  GetPublishingTokenTargetByIDRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  tokenID: z.string(),
});

/** @internal */
export type GetPublishingTokenTargetByIDRequest$Outbound = {
  tokenID: string;
};

/** @internal */
export const GetPublishingTokenTargetByIDRequest$outboundSchema: z.ZodType<
  GetPublishingTokenTargetByIDRequest$Outbound,
  z.ZodTypeDef,
  GetPublishingTokenTargetByIDRequest
> = z.object({
  tokenID: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPublishingTokenTargetByIDRequest$ {
  /** @deprecated use `GetPublishingTokenTargetByIDRequest$inboundSchema` instead. */
  export const inboundSchema =
    GetPublishingTokenTargetByIDRequest$inboundSchema;
  /** @deprecated use `GetPublishingTokenTargetByIDRequest$outboundSchema` instead. */
  export const outboundSchema =
    GetPublishingTokenTargetByIDRequest$outboundSchema;
  /** @deprecated use `GetPublishingTokenTargetByIDRequest$Outbound` instead. */
  export type Outbound = GetPublishingTokenTargetByIDRequest$Outbound;
}

export function getPublishingTokenTargetByIDRequestToJSON(
  getPublishingTokenTargetByIDRequest: GetPublishingTokenTargetByIDRequest,
): string {
  return JSON.stringify(
    GetPublishingTokenTargetByIDRequest$outboundSchema.parse(
      getPublishingTokenTargetByIDRequest,
    ),
  );
}

export function getPublishingTokenTargetByIDRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetPublishingTokenTargetByIDRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetPublishingTokenTargetByIDRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPublishingTokenTargetByIDRequest' from JSON`,
  );
}

/** @internal */
export const GetPublishingTokenTargetByIDResponseBody$inboundSchema: z.ZodType<
  GetPublishingTokenTargetByIDResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type GetPublishingTokenTargetByIDResponseBody$Outbound = {};

/** @internal */
export const GetPublishingTokenTargetByIDResponseBody$outboundSchema: z.ZodType<
  GetPublishingTokenTargetByIDResponseBody$Outbound,
  z.ZodTypeDef,
  GetPublishingTokenTargetByIDResponseBody
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPublishingTokenTargetByIDResponseBody$ {
  /** @deprecated use `GetPublishingTokenTargetByIDResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    GetPublishingTokenTargetByIDResponseBody$inboundSchema;
  /** @deprecated use `GetPublishingTokenTargetByIDResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    GetPublishingTokenTargetByIDResponseBody$outboundSchema;
  /** @deprecated use `GetPublishingTokenTargetByIDResponseBody$Outbound` instead. */
  export type Outbound = GetPublishingTokenTargetByIDResponseBody$Outbound;
}

export function getPublishingTokenTargetByIDResponseBodyToJSON(
  getPublishingTokenTargetByIDResponseBody:
    GetPublishingTokenTargetByIDResponseBody,
): string {
  return JSON.stringify(
    GetPublishingTokenTargetByIDResponseBody$outboundSchema.parse(
      getPublishingTokenTargetByIDResponseBody,
    ),
  );
}

export function getPublishingTokenTargetByIDResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  GetPublishingTokenTargetByIDResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetPublishingTokenTargetByIDResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetPublishingTokenTargetByIDResponseBody' from JSON`,
  );
}

/** @internal */
export const GetPublishingTokenTargetByIDResponse$inboundSchema: z.ZodType<
  GetPublishingTokenTargetByIDResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => GetPublishingTokenTargetByIDResponseBody$inboundSchema),
  shared.ErrorT$inboundSchema,
]);

/** @internal */
export type GetPublishingTokenTargetByIDResponse$Outbound =
  | GetPublishingTokenTargetByIDResponseBody$Outbound
  | shared.ErrorT$Outbound;

/** @internal */
export const GetPublishingTokenTargetByIDResponse$outboundSchema: z.ZodType<
  GetPublishingTokenTargetByIDResponse$Outbound,
  z.ZodTypeDef,
  GetPublishingTokenTargetByIDResponse
> = z.union([
  z.lazy(() => GetPublishingTokenTargetByIDResponseBody$outboundSchema),
  shared.ErrorT$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPublishingTokenTargetByIDResponse$ {
  /** @deprecated use `GetPublishingTokenTargetByIDResponse$inboundSchema` instead. */
  export const inboundSchema =
    GetPublishingTokenTargetByIDResponse$inboundSchema;
  /** @deprecated use `GetPublishingTokenTargetByIDResponse$outboundSchema` instead. */
  export const outboundSchema =
    GetPublishingTokenTargetByIDResponse$outboundSchema;
  /** @deprecated use `GetPublishingTokenTargetByIDResponse$Outbound` instead. */
  export type Outbound = GetPublishingTokenTargetByIDResponse$Outbound;
}

export function getPublishingTokenTargetByIDResponseToJSON(
  getPublishingTokenTargetByIDResponse: GetPublishingTokenTargetByIDResponse,
): string {
  return JSON.stringify(
    GetPublishingTokenTargetByIDResponse$outboundSchema.parse(
      getPublishingTokenTargetByIDResponse,
    ),
  );
}

export function getPublishingTokenTargetByIDResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetPublishingTokenTargetByIDResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetPublishingTokenTargetByIDResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPublishingTokenTargetByIDResponse' from JSON`,
  );
}
