/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as shared from "../shared/index.js";
import * as z from "zod";

export type GetRequestFromEventLogRequest = {
    /**
     * The ID of the request to retrieve.
     */
    requestID: string;
};

export type GetRequestFromEventLogResponse = shared.ErrorT | shared.UnboundedRequest;

/** @internal */
export const GetRequestFromEventLogRequest$inboundSchema: z.ZodType<
    GetRequestFromEventLogRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    requestID: z.string(),
});

/** @internal */
export type GetRequestFromEventLogRequest$Outbound = {
    requestID: string;
};

/** @internal */
export const GetRequestFromEventLogRequest$outboundSchema: z.ZodType<
    GetRequestFromEventLogRequest$Outbound,
    z.ZodTypeDef,
    GetRequestFromEventLogRequest
> = z.object({
    requestID: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetRequestFromEventLogRequest$ {
    /** @deprecated use `GetRequestFromEventLogRequest$inboundSchema` instead. */
    export const inboundSchema = GetRequestFromEventLogRequest$inboundSchema;
    /** @deprecated use `GetRequestFromEventLogRequest$outboundSchema` instead. */
    export const outboundSchema = GetRequestFromEventLogRequest$outboundSchema;
    /** @deprecated use `GetRequestFromEventLogRequest$Outbound` instead. */
    export type Outbound = GetRequestFromEventLogRequest$Outbound;
}

/** @internal */
export const GetRequestFromEventLogResponse$inboundSchema: z.ZodType<
    GetRequestFromEventLogResponse,
    z.ZodTypeDef,
    unknown
> = z.union([shared.ErrorT$inboundSchema, shared.UnboundedRequest$inboundSchema]);

/** @internal */
export type GetRequestFromEventLogResponse$Outbound =
    | shared.ErrorT$Outbound
    | shared.UnboundedRequest$Outbound;

/** @internal */
export const GetRequestFromEventLogResponse$outboundSchema: z.ZodType<
    GetRequestFromEventLogResponse$Outbound,
    z.ZodTypeDef,
    GetRequestFromEventLogResponse
> = z.union([shared.ErrorT$outboundSchema, shared.UnboundedRequest$outboundSchema]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetRequestFromEventLogResponse$ {
    /** @deprecated use `GetRequestFromEventLogResponse$inboundSchema` instead. */
    export const inboundSchema = GetRequestFromEventLogResponse$inboundSchema;
    /** @deprecated use `GetRequestFromEventLogResponse$outboundSchema` instead. */
    export const outboundSchema = GetRequestFromEventLogResponse$outboundSchema;
    /** @deprecated use `GetRequestFromEventLogResponse$Outbound` instead. */
    export type Outbound = GetRequestFromEventLogResponse$Outbound;
}
