/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetRevisionsRequest = {
  namespaceName: string;
  /**
   * Token to retrieve the next page of results
   */
  nextPageToken?: string | undefined;
};

/** @internal */
export const GetRevisionsRequest$inboundSchema: z.ZodType<
  GetRevisionsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  namespace_name: z.string(),
  next_page_token: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "namespace_name": "namespaceName",
    "next_page_token": "nextPageToken",
  });
});
/** @internal */
export type GetRevisionsRequest$Outbound = {
  namespace_name: string;
  next_page_token?: string | undefined;
};

/** @internal */
export const GetRevisionsRequest$outboundSchema: z.ZodType<
  GetRevisionsRequest$Outbound,
  z.ZodTypeDef,
  GetRevisionsRequest
> = z.object({
  namespaceName: z.string(),
  nextPageToken: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    namespaceName: "namespace_name",
    nextPageToken: "next_page_token",
  });
});

export function getRevisionsRequestToJSON(
  getRevisionsRequest: GetRevisionsRequest,
): string {
  return JSON.stringify(
    GetRevisionsRequest$outboundSchema.parse(getRevisionsRequest),
  );
}
export function getRevisionsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetRevisionsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetRevisionsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetRevisionsRequest' from JSON`,
  );
}
