/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GithubCheckPublishingSecretsRequest = {
  generateGenLockId: string;
};

/** @internal */
export const GithubCheckPublishingSecretsRequest$inboundSchema: z.ZodType<
  GithubCheckPublishingSecretsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  generate_gen_lock_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "generate_gen_lock_id": "generateGenLockId",
  });
});
/** @internal */
export type GithubCheckPublishingSecretsRequest$Outbound = {
  generate_gen_lock_id: string;
};

/** @internal */
export const GithubCheckPublishingSecretsRequest$outboundSchema: z.ZodType<
  GithubCheckPublishingSecretsRequest$Outbound,
  z.ZodTypeDef,
  GithubCheckPublishingSecretsRequest
> = z.object({
  generateGenLockId: z.string(),
}).transform((v) => {
  return remap$(v, {
    generateGenLockId: "generate_gen_lock_id",
  });
});

export function githubCheckPublishingSecretsRequestToJSON(
  githubCheckPublishingSecretsRequest: GithubCheckPublishingSecretsRequest,
): string {
  return JSON.stringify(
    GithubCheckPublishingSecretsRequest$outboundSchema.parse(
      githubCheckPublishingSecretsRequest,
    ),
  );
}
export function githubCheckPublishingSecretsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GithubCheckPublishingSecretsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GithubCheckPublishingSecretsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GithubCheckPublishingSecretsRequest' from JSON`,
  );
}
