/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RevokeUserAccessToWorkspaceGlobals = {
  workspaceId?: string | undefined;
};

export type RevokeUserAccessToWorkspaceRequest = {
  /**
   * Unique identifier of the workspace.
   */
  workspaceId?: string | undefined;
  /**
   * Unique identifier of the user.
   */
  userId: string;
};

/** @internal */
export const RevokeUserAccessToWorkspaceGlobals$inboundSchema: z.ZodType<
  RevokeUserAccessToWorkspaceGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  workspace_id: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "workspace_id": "workspaceId",
  });
});

/** @internal */
export type RevokeUserAccessToWorkspaceGlobals$Outbound = {
  workspace_id?: string | undefined;
};

/** @internal */
export const RevokeUserAccessToWorkspaceGlobals$outboundSchema: z.ZodType<
  RevokeUserAccessToWorkspaceGlobals$Outbound,
  z.ZodTypeDef,
  RevokeUserAccessToWorkspaceGlobals
> = z.object({
  workspaceId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    workspaceId: "workspace_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RevokeUserAccessToWorkspaceGlobals$ {
  /** @deprecated use `RevokeUserAccessToWorkspaceGlobals$inboundSchema` instead. */
  export const inboundSchema = RevokeUserAccessToWorkspaceGlobals$inboundSchema;
  /** @deprecated use `RevokeUserAccessToWorkspaceGlobals$outboundSchema` instead. */
  export const outboundSchema =
    RevokeUserAccessToWorkspaceGlobals$outboundSchema;
  /** @deprecated use `RevokeUserAccessToWorkspaceGlobals$Outbound` instead. */
  export type Outbound = RevokeUserAccessToWorkspaceGlobals$Outbound;
}

export function revokeUserAccessToWorkspaceGlobalsToJSON(
  revokeUserAccessToWorkspaceGlobals: RevokeUserAccessToWorkspaceGlobals,
): string {
  return JSON.stringify(
    RevokeUserAccessToWorkspaceGlobals$outboundSchema.parse(
      revokeUserAccessToWorkspaceGlobals,
    ),
  );
}

export function revokeUserAccessToWorkspaceGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<RevokeUserAccessToWorkspaceGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      RevokeUserAccessToWorkspaceGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RevokeUserAccessToWorkspaceGlobals' from JSON`,
  );
}

/** @internal */
export const RevokeUserAccessToWorkspaceRequest$inboundSchema: z.ZodType<
  RevokeUserAccessToWorkspaceRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  workspace_id: z.string().optional(),
  userId: z.string(),
}).transform((v) => {
  return remap$(v, {
    "workspace_id": "workspaceId",
  });
});

/** @internal */
export type RevokeUserAccessToWorkspaceRequest$Outbound = {
  workspace_id?: string | undefined;
  userId: string;
};

/** @internal */
export const RevokeUserAccessToWorkspaceRequest$outboundSchema: z.ZodType<
  RevokeUserAccessToWorkspaceRequest$Outbound,
  z.ZodTypeDef,
  RevokeUserAccessToWorkspaceRequest
> = z.object({
  workspaceId: z.string().optional(),
  userId: z.string(),
}).transform((v) => {
  return remap$(v, {
    workspaceId: "workspace_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RevokeUserAccessToWorkspaceRequest$ {
  /** @deprecated use `RevokeUserAccessToWorkspaceRequest$inboundSchema` instead. */
  export const inboundSchema = RevokeUserAccessToWorkspaceRequest$inboundSchema;
  /** @deprecated use `RevokeUserAccessToWorkspaceRequest$outboundSchema` instead. */
  export const outboundSchema =
    RevokeUserAccessToWorkspaceRequest$outboundSchema;
  /** @deprecated use `RevokeUserAccessToWorkspaceRequest$Outbound` instead. */
  export type Outbound = RevokeUserAccessToWorkspaceRequest$Outbound;
}

export function revokeUserAccessToWorkspaceRequestToJSON(
  revokeUserAccessToWorkspaceRequest: RevokeUserAccessToWorkspaceRequest,
): string {
  return JSON.stringify(
    RevokeUserAccessToWorkspaceRequest$outboundSchema.parse(
      revokeUserAccessToWorkspaceRequest,
    ),
  );
}

export function revokeUserAccessToWorkspaceRequestFromJSON(
  jsonString: string,
): SafeParseResult<RevokeUserAccessToWorkspaceRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      RevokeUserAccessToWorkspaceRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RevokeUserAccessToWorkspaceRequest' from JSON`,
  );
}
