/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { organizationsActivateLanguage } from "../funcs/organizationsActivateLanguage.js";
import { organizationsCancelSubscription } from "../funcs/organizationsCancelSubscription.js";
import { organizationsCreate } from "../funcs/organizationsCreate.js";
import { organizationsCreateBillingAddOns } from "../funcs/organizationsCreateBillingAddOns.js";
import { organizationsCreateFreeTrial } from "../funcs/organizationsCreateFreeTrial.js";
import { organizationsCreateLanguageCheckoutSession } from "../funcs/organizationsCreateLanguageCheckoutSession.js";
import { organizationsDeactivateLanguage } from "../funcs/organizationsDeactivateLanguage.js";
import { organizationsDeleteBillingAddOn } from "../funcs/organizationsDeleteBillingAddOn.js";
import { organizationsGet } from "../funcs/organizationsGet.js";
import { organizationsGetAll } from "../funcs/organizationsGetAll.js";
import { organizationsGetBillingAddOns } from "../funcs/organizationsGetBillingAddOns.js";
import { organizationsGetBillingEmail } from "../funcs/organizationsGetBillingEmail.js";
import { organizationsGetBillingOperations } from "../funcs/organizationsGetBillingOperations.js";
import { organizationsGetBusinessTierPrices } from "../funcs/organizationsGetBusinessTierPrices.js";
import { organizationsGetLanguages } from "../funcs/organizationsGetLanguages.js";
import { organizationsGetSubscription } from "../funcs/organizationsGetSubscription.js";
import { organizationsGetTrialTargets } from "../funcs/organizationsGetTrialTargets.js";
import { organizationsGetUsage } from "../funcs/organizationsGetUsage.js";
import { organizationsHandleCheckoutCallback } from "../funcs/organizationsHandleCheckoutCallback.js";
import { organizationsRevertSubscriptionCancellation } from "../funcs/organizationsRevertSubscriptionCancellation.js";
import { organizationsUpsertBillingEmail } from "../funcs/organizationsUpsertBillingEmail.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import * as shared from "./models/shared/index.js";
import { unwrapAsync } from "./types/fp.js";

export class Organizations extends ClientSDK {
  /**
   * Activate language
   *
   * @remarks
   * Activates a language for billing. If the language was previously deactivated,
   * this will reactivate it. If the language is new, it may require checkout.
   */
  async activateLanguage(
    request: operations.ActivateLanguageRequest,
    options?: RequestOptions,
  ): Promise<shared.LanguageActivationResponse> {
    return unwrapAsync(organizationsActivateLanguage(
      this,
      request,
      options,
    ));
  }

  /**
   * Cancel subscription
   *
   * @remarks
   * Requests cancellation of the organization's self-service business subscription.
   * The subscription will be cancelled at the end of the current billing period.
   * Specify a target to keep after downgrade to free tier when active targets remain.
   */
  async cancelSubscription(
    request: shared.CancelSubscriptionRequest,
    options?: RequestOptions,
  ): Promise<shared.CancelSubscriptionResponse> {
    return unwrapAsync(organizationsCancelSubscription(
      this,
      request,
      options,
    ));
  }

  /**
   * Create an organization
   *
   * @remarks
   * Creates an organization
   */
  async create(
    request: shared.Organization,
    options?: RequestOptions,
  ): Promise<shared.Organization> {
    return unwrapAsync(organizationsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Create billing add ons
   */
  async createBillingAddOns(
    request: shared.OrganizationBillingAddOnRequest,
    options?: RequestOptions,
  ): Promise<shared.OrganizationBillingAddOnResponse> {
    return unwrapAsync(organizationsCreateBillingAddOns(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a free trial for an organization
   *
   * @remarks
   * Creates a free trial for an organization
   */
  async createFreeTrial(
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(organizationsCreateFreeTrial(
      this,
      options,
    ));
  }

  /**
   * Create language checkout session
   *
   * @remarks
   * Creates a Stripe checkout session for per-language billing.
   * Used when upgrading to business tier with per-language billing model.
   */
  async createLanguageCheckoutSession(
    request: shared.CreateLanguageCheckoutSessionRequest,
    options?: RequestOptions,
  ): Promise<shared.CreateCheckoutSessionResponse> {
    return unwrapAsync(organizationsCreateLanguageCheckoutSession(
      this,
      request,
      options,
    ));
  }

  /**
   * Deactivate language
   *
   * @remarks
   * Deactivates a language. Subject to 2-week cooldown between deactivations.
   */
  async deactivateLanguage(
    request: operations.DeactivateLanguageRequest,
    options?: RequestOptions,
  ): Promise<shared.LanguageActivationResponse> {
    return unwrapAsync(organizationsDeactivateLanguage(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete billing add ons
   */
  async deleteBillingAddOn(
    request: operations.DeleteBillingAddOnRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(organizationsDeleteBillingAddOn(
      this,
      request,
      options,
    ));
  }

  /**
   * Get organization
   *
   * @remarks
   * Get information about a particular organization.
   */
  async get(
    request: operations.GetOrganizationRequest,
    options?: RequestOptions,
  ): Promise<shared.Organization> {
    return unwrapAsync(organizationsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Get organizations for a user
   *
   * @remarks
   * Returns a list of organizations a user has access too
   */
  async getAll(
    options?: RequestOptions,
  ): Promise<Array<shared.Organization>> {
    return unwrapAsync(organizationsGetAll(
      this,
      options,
    ));
  }

  /**
   * Get billing add ons
   */
  async getBillingAddOns(
    options?: RequestOptions,
  ): Promise<shared.OrganizationBillingAddOnResponse> {
    return unwrapAsync(organizationsGetBillingAddOns(
      this,
      options,
    ));
  }

  /**
   * Get billing email for an organization
   *
   * @remarks
   * Returns the billing email and Stripe customer status for the current organization
   */
  async getBillingEmail(
    options?: RequestOptions,
  ): Promise<shared.BillingEmailResponse> {
    return unwrapAsync(organizationsGetBillingEmail(
      this,
      options,
    ));
  }

  /**
   * Get billing operations breakdown for an organization
   *
   * @remarks
   * Returns a breakdown of billing operations by language and generated SDK target
   * for an organization. Each language row is sourced from generation events,
   * and target rows optionally include the source spec namespace when available.
   */
  async getBillingOperations(
    options?: RequestOptions,
  ): Promise<shared.BillingOperationsResponse> {
    return unwrapAsync(organizationsGetBillingOperations(
      this,
      options,
    ));
  }

  /**
   * Get business tier prices
   *
   * @remarks
   * Returns both monthly and annual business tier prices from Stripe
   */
  async getBusinessTierPrices(
    options?: RequestOptions,
  ): Promise<shared.BusinessTierPricesResponse> {
    return unwrapAsync(organizationsGetBusinessTierPrices(
      this,
      options,
    ));
  }

  /**
   * Get language billing configurations
   *
   * @remarks
   * Returns all language billing configurations for the organization.
   * Only returns languages with self-serve billing configured.
   */
  async getLanguages(
    options?: RequestOptions,
  ): Promise<shared.GetLanguagesResponse> {
    return unwrapAsync(organizationsGetLanguages(
      this,
      options,
    ));
  }

  /**
   * Get organization subscription
   *
   * @remarks
   * Returns the subscription status for the current organization
   */
  async getSubscription(
    options?: RequestOptions,
  ): Promise<shared.OrganizationSubscriptionResponse> {
    return unwrapAsync(organizationsGetSubscription(
      this,
      options,
    ));
  }

  /**
   * Get trial targets
   *
   * @remarks
   * Returns the list of target languages with available and used trials for the organization.
   * Available trials are languages that have not yet been trialed.
   * Used trials are languages that have already been trialed.
   */
  async getTrialTargets(
    options?: RequestOptions,
  ): Promise<shared.TrialTargetsResponse> {
    return unwrapAsync(organizationsGetTrialTargets(
      this,
      options,
    ));
  }

  /**
   * Get billing usage summary for a particular organization
   *
   * @remarks
   * Returns a billing usage summary by target languages for a particular organization
   */
  async getUsage(
    options?: RequestOptions,
  ): Promise<shared.OrganizationUsageResponse> {
    return unwrapAsync(organizationsGetUsage(
      this,
      options,
    ));
  }

  /**
   * Checkout callback
   *
   * @remarks
   * Handles the Stripe checkout success callback. This endpoint is called by Stripe
   * after a successful checkout, runs reconciliation (idempotent), and redirects
   * to the original client success URL stored in session metadata.
   */
  async handleCheckoutCallback(
    request: operations.HandleCheckoutCallbackRequest,
    options?: RequestOptions,
  ): Promise<operations.HandleCheckoutCallbackResponse | undefined> {
    return unwrapAsync(organizationsHandleCheckoutCallback(
      this,
      request,
      options,
    ));
  }

  /**
   * Revert subscription cancellation
   *
   * @remarks
   * Reverts a pending subscription cancellation.
   * The subscription will continue to renew automatically.
   */
  async revertSubscriptionCancellation(
    options?: RequestOptions,
  ): Promise<shared.CancelSubscriptionResponse> {
    return unwrapAsync(organizationsRevertSubscriptionCancellation(
      this,
      options,
    ));
  }

  /**
   * Create or update billing email
   *
   * @remarks
   * Creates a Stripe customer if one does not exist, or updates the billing email for an existing Stripe customer
   */
  async upsertBillingEmail(
    request: shared.BillingEmailRequest,
    options?: RequestOptions,
  ): Promise<shared.BillingEmailResponse> {
    return unwrapAsync(organizationsUpsertBillingEmail(
      this,
      request,
      options,
    ));
  }
}
