/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { schemaStoreCreateSchemaStoreItem } from "../funcs/schemaStoreCreateSchemaStoreItem.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import * as shared from "./models/shared/index.js";
import { unwrapAsync } from "./types/fp.js";

export class SchemaStore extends ClientSDK {
  /**
   * Create a schema in the schema store
   */
  async createSchemaStoreItem(
    request: operations.CreateSchemaStoreItemRequestBody,
    options?: RequestOptions,
  ): Promise<shared.SchemaStoreItem> {
    return unwrapAsync(schemaStoreCreateSchemaStoreItem(
      this,
      request,
      options,
    ));
  }
}
