/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsActivateSubscriptionNamespace } from "../funcs/subscriptionsActivateSubscriptionNamespace.js";
import { subscriptionsIgnoreSubscriptionNamespace } from "../funcs/subscriptionsIgnoreSubscriptionNamespace.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import * as shared from "./models/shared/index.js";
import { unwrapAsync } from "./types/fp.js";

export class Subscriptions extends ClientSDK {
  /**
   * Activate an ignored namespace for a subscription
   */
  async activateSubscriptionNamespace(
    request: operations.ActivateSubscriptionNamespaceRequest,
    options?: RequestOptions,
  ): Promise<shared.ErrorT | undefined> {
    return unwrapAsync(subscriptionsActivateSubscriptionNamespace(
      this,
      request,
      options,
    ));
  }

  /**
   * Ignored a namespace for a subscription
   */
  async ignoreSubscriptionNamespace(
    request: operations.IgnoreSubscriptionNamespaceRequest,
    options?: RequestOptions,
  ): Promise<shared.ErrorT | undefined> {
    return unwrapAsync(subscriptionsIgnoreSubscriptionNamespace(
      this,
      request,
      options,
    ));
  }
}
