/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsCreateSubscription } from "../funcs/subscriptionsCreateSubscription.js";
import { subscriptionsListSubscriptions } from "../funcs/subscriptionsListSubscriptions.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import * as shared from "./models/shared/index.js";
import { unwrapAsync } from "./types/fp.js";

export class Subscriptions extends ClientSDK {
  /**
   * Create Subscription
   */
  async createSubscription(
    request: operations.CreateSubscriptionRequest,
    options?: RequestOptions,
  ): Promise<shared.Subscription> {
    return unwrapAsync(subscriptionsCreateSubscription(
      this,
      request,
      options,
    ));
  }

  /**
   * List Subscriptions
   */
  async listSubscriptions(
    request: operations.ListSubscriptionsRequest,
    options?: RequestOptions,
  ): Promise<Array<shared.Subscription>> {
    return unwrapAsync(subscriptionsListSubscriptions(
      this,
      request,
      options,
    ));
  }
}
