workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: https://speakeasy.com/openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/speakeasy-self/speakeasy-self/my-source
targets:
    speakeasy-client-sdk-typescript:
        target: typescript
        source: my-source
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/speakeasy-self/speakeasy-self/my-source-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
